#!/usr/bin/env bash
set -euo pipefail
: "${API_TOKEN:?API_TOKEN required}"
BASE="${HOSTINGER_API_BASE:-https://developers.hostinger.com}"; VM_ID="${VM_ID:-767852}"; HOST="${HOST:-69.62.68.67}"
api(){ curl -sS -H "Authorization: Bearer $API_TOKEN" -H 'Accept: application/json' "$@"; }
wait_idle(){ for i in $(seq 1 180); do b="$(api "$BASE/api/vps/v1/virtual-machines/$VM_ID/actions?page=1")"; n="$(jq '[.data[]?|select((.state//"")|test("^(sent|started|pending|running|queued)$"))]|length'<<<"$b")"; [[ "$n" == 0 ]]&&{ echo HOSTINGER_ACTION_PLANE=IDLE; return; }; echo "HOSTINGER_ACTION_PLANE=BUSY count=$n probe=$i"; sleep 5; done; return 20; }
start_recovery(){ : "${RECOVERY_PASSWORD:?RECOVERY_PASSWORD required}"; p="$(jq -n --arg p "$RECOVERY_PASSWORD" '{root_password:$p}')"; for a in $(seq 1 8); do wait_idle; t="$(mktemp)"; c="$(curl -sS -o "$t" -w '%{http_code}' -X POST -H "Authorization: Bearer $API_TOKEN" -H 'Content-Type: application/json' -H 'Accept: application/json' --data "$p" "$BASE/api/vps/v1/virtual-machines/$VM_ID/recovery")"; b="$(cat "$t")"; rm -f "$t"; if [[ "$c" =~ ^20[012]$ ]]; then id="$(jq -r '.id//empty'<<<"$b")"; [[ "$id" =~ ^[1-9][0-9]*$ ]]||return 21; echo "$id"; return; fi; echo "RECOVERY_START_RETRY=$a HTTP=$c" >&2; jq -c .<<<"$b" >&2 2>/dev/null||true; [[ "$c" =~ ^(403|409|422|423|429|500|502|503|504)$ ]]||return 22; sleep $((a*10)); done; return 23; }
wait_action(){ id="$1"; for i in $(seq 1 180); do b="$(api "$BASE/api/vps/v1/virtual-machines/$VM_ID/actions/$id")"; s="$(jq -r '.state//empty'<<<"$b")"; echo "ACTION=$id STATE=$s PROBE=$i" >&2; [[ "$s" == success ]]&&return; [[ "$s" =~ ^(failed|failure|error|cancelled|canceled)$ ]]&&return 24; sleep 5; done; return 25; }
case "${1:-diagnose}" in diagnose) vm="$(api "$BASE/api/vps/v1/virtual-machines/$VM_ID")"; ac="$(api "$BASE/api/vps/v1/virtual-machines/$VM_ID/actions?page=1")"; tcp="$(nc -z -w4 "$HOST" 22&&echo open||echo closed)"; jq -n --argjson vm "$vm" --argjson ac "$ac" --arg tcp "$tcp" '{vm:{id:$vm.id,state:$vm.state,is_running:$vm.is_running,is_recovery_mode:$vm.is_recovery_mode,actions_lock:$vm.actions_lock},tcp22:$tcp,active_actions:[$ac.data[]?|select((.state//"")|test("^(sent|started|pending|running|queued)$"))|{id,name,state}]}';; wait-idle) wait_idle;; start-recovery) start_recovery;; wait-action) wait_action "${2:?action id}";; *) exit 64;; esac
