"""Source-backed Cuba prospects. Commercial proposals are explicitly inferred."""
RESEARCHED_ON = '2026-09-10'
PROSPECTS = [
    {'id': 'renova', 'business_name': 'RENOVA', 'province': 'Camagüey', 'sector': 'Solar y respaldo',
     'observed_activity': 'Publica paneles solares y proyectos de instalación en Cuba.',
     'proposal': 'Explorar suministro de módulos solares para instalaciones de hogares y negocios privados.',
     'source_url': 'https://www.renovacuba.com/',
     'evidence_urls': ['https://www.renovacuba.com/proyectos', 'https://www.ipscuba.net/especial/nuevos-actores-economicos/assets/store/files/directorio-nuevos-actores-economicos.pdf'],
     'supplier_ids': ['longi'], 'ownership_evidence': 'Directorio IPS identifica a Renova como mipyme privada; confirmar entidad legal y control actuales.'},
    {'id': 'suncar', 'business_name': 'SunCar Cuba', 'province': 'La Habana', 'sector': 'Solar y respaldo',
     'observed_activity': 'Su web ofrece paneles solares, baterías e instalación para hogares y negocios.',
     'proposal': 'Explorar abastecimiento de módulos y componentes de instalación solar.',
     'source_url': 'https://www.suncarsrl.com/', 'evidence_urls': ['https://www.suncarsrl.com/contacto'],
     'supplier_ids': ['longi', 'abb'], 'ownership_evidence': 'Perfil comercial encontrado; propiedad privada y entidad contratante pendientes de confirmar.'},
    {'id': 'mercatoria', 'business_name': 'Mercatoria', 'province': 'La Habana', 'sector': 'Alimentos y distribución',
     'observed_activity': 'Publica distribución mayorista de alimentos, congelados e insumos para gastronomía; su tienda entrega en Cuba.',
     'proposal': 'Explorar reposición de alimentos secos, conservas e ingredientes para distribución privada.',
     'source_url': 'https://mercatoria.us/', 'evidence_urls': ['https://www.mercatoria.store/faq', 'https://linktr.ee/mercatoria_cuba'],
     'supplier_ids': ['arcor', 'olam-india', 'graincorp'], 'ownership_evidence': 'La web identifica a un socio fundador. Confirmar la entidad cubana compradora y sus beneficiarios.'},
    {'id': 'granado', 'business_name': 'Producciones Granado', 'province': 'La Habana', 'sector': 'Alimentos y frío',
     'observed_activity': 'CEMÍS describe producción de alimentos congelados, gelato y catering. El perfil no especifica qué busca comprar.',
     'proposal': 'Explorar ingredientes lácteos para gelato y necesidades de conservación en frío.',
     'source_url': 'https://cemis.io/empresas/producciones-granado.html', 'evidence_urls': [],
     'supplier_ids': ['fonterra'], 'ownership_evidence': 'CEMÍS la clasifica como MIPYME Privada; esa clasificación no sustituye KYB.'},
    {'id': 'dmc', 'business_name': 'DMC S.R.L.', 'province': 'La Habana', 'sector': 'Hospitalidad y energía',
     'observed_activity': 'CEMÍS describe turismo receptivo y una ampliación proyectada hacia equipamiento de alojamientos y respaldo fotovoltaico.',
     'proposal': 'Validar si la ampliación está vigente y si existen compras previstas de módulos solares para alojamientos privados.',
     'source_url': 'https://www.cemis.io/empresas/dmc-srl.html', 'evidence_urls': [],
     'supplier_ids': ['longi'], 'ownership_evidence': 'CEMÍS la clasifica como MIPYME Privada; el alcance ampliado figuraba en trámite, no como autorización confirmada.'},
    {'id': 'propersa', 'business_name': 'Mercado Propersa', 'province': 'La Habana', 'sector': 'Alimentos y retail',
     'observed_activity': 'Publica comercio minorista de alimentos, bebidas y artículos de aseo, con tienda en Plaza de la Revolución.',
     'proposal': 'Explorar reposición de alimentos envasados para su tienda y cafetería.',
     'source_url': 'https://propersa.com/acerca-de/', 'evidence_urls': [],
     'supplier_ids': ['arcor', 'olam-india'], 'ownership_evidence': 'Perfil comercial encontrado; verificar propiedad privada y entidad legal antes de calificar.'},
]
for prospect in PROSPECTS:
    prospect.update(status='RESEARCH_PROSPECT', researched_on=RESEARCHED_ON, destination_country='CU',
                    demand_confirmed=False, estimated_deal_value=None, consent_to_business_contact=False,
                    next_step='Confirmar propiedad privada, comprador autorizado, producto/especificación, cantidad, presupuesto, plazo, origen y condiciones de entrega.')
