from __future__ import annotations

import secrets
from datetime import datetime, timezone

from insforge_backend import get_backend
from lead_scout_api import LeadScoutIn, fingerprint, opportunity_score, priority


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


ENERGY_CRM_LEADS = [
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "A Granel",
        "country": "CU",
        "city_region": "Havana",
        "deal_side": "BOTH",
        "lead_type": "DISTRIBUTOR",
        "product_need_or_offer": "Private-sector fuel distributor in Cuba selling imported U.S. diesel to registered private businesses; candidate buyer/distribution partner for U.S.-origin gasoline and diesel.",
        "source_url": "https://www.reuters.com/business/energy/us-fuel-sales-cuban-business-bring-glimpse-capitalism-havana-2026-08-11/",
        "source_description": "Reuters coverage of U.S.-origin fuel sales to Cuba private sector",
        "evidence_urls": ["https://www.reuters.com/business/energy/us-fuel-sales-cuban-business-bring-glimpse-capitalism-havana-2026-08-11/"],
        "notes": "CUBA_ENERGY; CUBA_FUELS; GASOLINE_DIESEL. Verify private ownership, end use, BIS/OFAC eligibility, payment rail and logistics before any transaction.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "Katapulk",
        "email": "info@katapulk.com",
        "country": "US",
        "deal_side": "BOTH",
        "lead_type": "PARTNER",
        "product_need_or_offer": "U.S.-to-Cuba fuel delivery channel advertising gasoline/diesel supply and ISO-tank delivery options; potential wholesale, reseller or referral partner.",
        "source_url": "https://oncubanews.com/publirreportaje/katapulk-ofrece-combustible-a-las-mipymes-cubanas-canales-seguros-para-nuestros-clientes/",
        "source_description": "Public commercial coverage of Katapulk Cuba fuel offering",
        "evidence_urls": ["https://oncubanews.com/publirreportaje/katapulk-ofrece-combustible-a-las-mipymes-cubanas-canales-seguros-para-nuestros-clientes/"],
        "notes": "CUBA_ENERGY; CUBA_FUELS; DISTRIBUTION_CHANNEL. Outreach sent. Awaiting wholesale pricing, capacity, delivery points, KYC/KYB and partner economics.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "MiPymeCombustible",
        "email": "control@mipymecombustible.com",
        "country": "US",
        "deal_side": "BOTH",
        "lead_type": "PARTNER",
        "product_need_or_offer": "Fuel platform targeting Cuban private-sector gasoline and diesel import/direct-supply workflows; potential wholesale/partner channel pending enhanced KYB.",
        "source_url": "https://mipymecombustible.com/",
        "source_description": "Company public website; claims require independent verification",
        "evidence_urls": ["https://mipymecombustible.com/"],
        "notes": "CUBA_ENERGY; CUBA_FUELS; DISTRIBUTION_CHANNEL; ENHANCED_KYB_REQUIRED. Outreach sent for wholesale terms and compliance path.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "IslaDiesel",
        "email": "contacto@isladiesel.com",
        "country": "US",
        "deal_side": "BOTH",
        "lead_type": "PARTNER",
        "product_need_or_offer": "Collective-purchase commercial channel advertising diesel and gasoline supply to Cuba; potential wholesale or referral partner.",
        "source_url": "https://isladiesel.com/",
        "source_description": "Public company website",
        "evidence_urls": ["https://isladiesel.com/"],
        "notes": "CUBA_ENERGY; CUBA_FUELS; DISTRIBUTION_CHANNEL. Outreach sent. Verify entity, capacity, U.S.-origin supply, payment rail, delivery model and partner economics.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "RENOVA S.R.L.",
        "email": "info@renova.cu",
        "phone": "+53 59880000",
        "country": "CU",
        "city_region": "Camaguey",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Private renewable-energy company with a substantial installed project base; broader energy-sector prospect for international equipment sourcing.",
        "source_url": "https://www.renovacuba.com/",
        "source_description": "Official company website and email acknowledgment",
        "evidence_urls": ["https://www.renovacuba.com/"],
        "notes": "CUBA_ENERGY; CUBA_RENEWABLES; SOLAR_STORAGE. Human response pending. Keep separate from Cuba fuels unless direct gasoline/diesel demand is established.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "MPM XPROYECTO.CU SURL",
        "contact_name": "Oscar Lamothe Vaillant",
        "country": "CU",
        "deal_side": "BUYER",
        "lead_type": "PARTNER",
        "product_need_or_offer": "AGRORENEW agroindustrial project. Current priority is an investment partner; future international sourcing demand includes machinery, irrigation systems and energy components.",
        "source_url": "https://xproyecto.cu/",
        "source_description": "Direct business response and company website",
        "evidence_urls": ["https://xproyecto.cu/"],
        "notes": "CUBA_ENERGY; CUBA_AGRO_ENERGY; ENERGY_INVESTMENT. Qualified strategic/investment opportunity. Request full investor package before committing resources.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "SunCar Cuba",
        "country": "CU",
        "city_region": "Playa, Havana",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Solar installation, batteries, maintenance and energy consulting business; broader energy-sector prospect.",
        "source_url": "https://suncarsrl.com/contacto",
        "source_description": "Official company website",
        "evidence_urls": ["https://suncarsrl.com/contacto"],
        "notes": "CUBA_ENERGY; CUBA_RENEWABLES; SOLAR_STORAGE. Ownership/KYB verification required. Keep separate from Cuba gasoline/diesel unless direct fuel demand is established.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "MAXTEC S.U.R.L.",
        "email": "atencionalcliente@maxteccuba.com",
        "phone": "+53 50961867",
        "country": "CU",
        "city_region": "Sagua de Tanamo / Moa",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Private MIPYME in technology, telecom, repair, installation and commercial products; energy-adjacent prospect for backup power and related equipment.",
        "source_url": "https://maxteccuba.com/",
        "source_description": "Official company website",
        "evidence_urls": ["https://maxteccuba.com/"],
        "notes": "CUBA_ENERGY; CUBA_ENERGY_INFRASTRUCTURE; BACKUP_POWER. KYB and specific demand required.",
    },
    {
        "scout_name": "SAHJONY CEO Energy Origination",
        "business_name": "Frenas Conmigo S.U.R.L.",
        "contact_name": "Alvaro Grass Gonzalez",
        "country": "CU",
        "city_region": "Holguin",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Private small enterprise operating photovoltaic charging infrastructure in Holguin; broader energy-sector prospect with possible expansion needs.",
        "source_url": "https://www.granma.cu/cuba/2026-06-15/holguin-cuenta-con-su-primera-electrolinera-fotovoltaica-15-06-2026-23-06-19",
        "source_description": "Public reporting on private photovoltaic charging station",
        "evidence_urls": ["https://www.granma.cu/cuba/2026-06-15/holguin-cuenta-con-su-primera-electrolinera-fotovoltaica-15-06-2026-23-06-19"],
        "notes": "CUBA_ENERGY; CUBA_RENEWABLES; EV_CHARGING. No validated direct contact yet. Verify corporate registration and current demand.",
    },
    {
        "scout_name": "SAHJONY CEO Cuba Energy Origination",
        "business_name": "Grupo Nueva Vision",
        "phone": "+53 54421417",
        "country": "CU",
        "city_region": "Diez de Octubre, Havana",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Cuban private MIPYME publicly advertising photovoltaic panels, inverters, EcoFlow systems, refrigeration and electrical services for households and businesses in Havana; prospect for energy equipment sourcing and commercial partnerships.",
        "source_url": "https://itencel.com/anuncio/instalacion-paneles-solares-y-servicios-de-clima-y-refrigeracion/",
        "source_description": "Public commercial listing identifying Grupo Nueva Vision as a MIPYME providing solar and refrigeration services in Havana.",
        "evidence_urls": ["https://itencel.com/anuncio/instalacion-paneles-solares-y-servicios-de-clima-y-refrigeracion/", "https://www.revolico.com/item/instalacion-paneles-inversor-ecoflow-54746988"],
        "notes": "CUBA_ENERGY; CUBA_RENEWABLES; SOLAR_STORAGE; ENERGY_INFRASTRUCTURE. Verify corporate registration, ownership, current demand and export-control eligibility before commitment.",
    },
    {
        "scout_name": "SAHJONY CEO Cuba Energy Origination",
        "business_name": "Fujian Trebor Trading Company",
        "country": "CN",
        "city_region": "Representation reported in Miramar, Havana, Cuba",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Foreign fuel supply channel publicly reported offering gasoline and diesel to Cuban MIPYMES in 25,000-liter lots, with commercial activity in Havana. Candidate Cuba-energy supplier lead subject to enhanced KYB, origin verification and sanctions/export-control review.",
        "source_url": "https://www.14ymedio.com/cuba/pese-cerco-energetico-impuesto-ee_1_1123892.html",
        "source_description": "Public reporting identifies Fujian Trebor Trading Company as offering gasoline and diesel to Cuban private businesses in 25,000-liter lots.",
        "evidence_urls": ["https://www.14ymedio.com/cuba/pese-cerco-energetico-impuesto-ee_1_1123892.html", "https://www.cibercuba.com/noticias/2026-02-23-u1-e129488-s27061-nid321483-empresa-china-cuba-importa-combustible-venta-dolares"],
        "notes": "CUBA_ENERGY; CUBA_FUELS; FUEL_SUPPLY_CHANNEL; ENHANCED_KYB_REQUIRED. Do not infer U.S.-law eligibility or product origin from media claims.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Hindustan Petroleum Corporation Limited (HPCL)",
        "country": "IN",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Institutional crude buyer. Recent spot requirement sought up to 4,000,000 barrels for September/October delivery; SAHJONY outreach sent for approved counterparty/trader registration.",
        "estimated_deal_value": 300000000,
        "source_url": "https://www.reuters.com/business/energy/indias-hpcl-mrpl-seek-up-six-million-barrels-crude-documents-show-2026-08-12/",
        "source_description": "Reuters current crude procurement report",
        "evidence_urls": ["https://www.reuters.com/business/energy/indias-hpcl-mrpl-seek-up-six-million-barrels-crude-documents-show-2026-08-12/", "https://www.hindustanpetroleum.com/hp-international-trade"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Tender status/deadline and approved counterparty registration must be confirmed.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Mangalore Refinery and Petrochemicals Limited (MRPL)",
        "email": "eps@mrpl.co.in",
        "country": "IN",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Institutional refinery crude buyer. Recent requirement sought up to 2,000,000 barrels for October delivery; SAHJONY outreach sent to procurement contact.",
        "estimated_deal_value": 150000000,
        "source_url": "https://www.reuters.com/business/energy/indias-hpcl-mrpl-seek-up-six-million-barrels-crude-documents-show-2026-08-12/",
        "source_description": "Reuters current crude procurement report and MRPL procurement channel",
        "evidence_urls": ["https://www.reuters.com/business/energy/indias-hpcl-mrpl-seek-up-six-million-barrels-crude-documents-show-2026-08-12/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Buyer registration and tender access pending.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Indian Oil Corporation Limited (IndianOil)",
        "country": "IN",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Recurring institutional crude importer using approved supplier/buyer mailing lists and tender procurement. SAHJONY outreach sent for crude counterparty registration path.",
        "source_url": "https://iocl.com/import-export",
        "source_description": "IndianOil official import/export and registration information",
        "evidence_urls": ["https://iocl.com/import-export", "https://www.iocletenders.nic.in/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Strategic recurring buyer; approved counterparty status required before tender participation.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Abu Dhabi National Oil Company (ADNOC)",
        "country": "AE",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Major crude supplier with repeated 2026 spot tenders offering Murban, Upper Zakum, Umm Lulu and Das grades; institutional supply-side opportunity subject to tender access and current deadline verification.",
        "source_url": "https://www.reuters.com/business/energy/adnoc-unbound-war-opec-exit-launch-emirates-oil-giant-quest-growth-2026-08-13/",
        "source_description": "Reuters reporting on ADNOC expanded spot crude sales",
        "evidence_urls": ["https://www.reuters.com/business/energy/adnoc-unbound-war-opec-exit-launch-emirates-oil-giant-quest-growth-2026-08-13/"],
        "notes": "GLOBAL_CRUDE; SELLER_SUPPLIER. Outside Cuba. Do not treat as available allocation unless tender access and seller authority are independently verified.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "CPC Corporation Taiwan",
        "country": "TW",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Recurring crude buyer that procures spot cargoes from approved counterparties and recently purchased U.S. and West African crude; suitable only if SAHJONY qualifies as an approved trader.",
        "source_url": "https://www.cpc.com.tw/",
        "source_description": "CPC procurement information and recent market purchases",
        "evidence_urls": ["https://www.cpc.com.tw/", "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Approved counterparty status required; pure intermediary route is a poor fit.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "GS Caltex",
        "country": "KR",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "South Korean refinery buyer recently reported purchasing 2,000,000 barrels of Mars crude from Shell; candidate recurring U.S.-crude buyer for institutional origination.",
        "estimated_deal_value": 180000000,
        "source_url": "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/",
        "source_description": "Reuters report on Asian refinery crude purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Recent purchase is market intelligence, not a current open RFQ unless confirmed.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Eneos Corporation",
        "country": "JP",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Japanese refiner recently reported purchasing WTI crude as Asian refiners diversify supply; candidate recurring institutional crude buyer.",
        "source_url": "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/",
        "source_description": "Reuters report on Asian refinery crude purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Current open procurement requirement must be confirmed before supplier outreach.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Cosmo Energy Holdings",
        "country": "JP",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Japanese refiner recently reported purchasing Mars crude; candidate recurring institutional U.S.-crude buyer.",
        "source_url": "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/",
        "source_description": "Reuters report on Asian refinery crude purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Current open procurement requirement must be confirmed.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Joel Campble / Jocam Deal",
        "contact_name": "Joel Campble",
        "email": "info@jocamdeal.com",
        "country": "US",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace RFQs list approximately 1,000,000 barrels of crude oil and 1,000,000 barrels of A1 jet fuel, CIF or FOB, with L/C or SBLC terms; buyer authority remains unverified.",
        "estimated_deal_value": 90000000,
        "source_url": "https://www.go4worldbusiness.com/",
        "source_description": "go4WorldBusiness buyer alert dated August 24, 2026",
        "evidence_urls": ["https://www.go4worldbusiness.com/"],
        "notes": "GLOBAL_CRUDE; REFINED_PRODUCTS; JET_A1; BUYER_AUTHORITY_UNVERIFIED. Require buyer legal entity, authority, destination, grade, LOI/ICPO and reasonable RWA evidence before sourcing cargo.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Bharat Petroleum Corporation Limited (BPCL)",
        "country": "IN",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Large Indian state refiner and recurring petroleum importer; relevant institutional buyer for crude and U.S.-origin LPG procurement programs alongside IOC and HPCL.",
        "source_url": "https://www.bharatpetroleum.in/",
        "source_description": "Official BPCL corporate source and current Indian energy procurement context",
        "evidence_urls": ["https://www.bharatpetroleum.in/", "https://www.reuters.com/business/energy/indian-oil-close-signing-lpg-import-deal-with-algerias-sonatrach-2027-sources-2026-08-20/"],
        "notes": "GLOBAL_CRUDE; BUYER. Outside Cuba. Specific crude procurement/tender must be independently confirmed before presenting supply.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Saudi Aramco",
        "country": "SA",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Major crude supplier reported offering Arab Medium and Arab Heavy to Asian refiners through alternative loading arrangements, with Arab Light rerouted through non-Hormuz export points.",
        "source_url": "https://www.reuters.com/business/energy/saudi-aramco-offers-crude-outside-hormuz-some-asian-refiners-sources-say-2026-08-17/",
        "source_description": "Reuters report on current crude supply offers",
        "evidence_urls": ["https://www.reuters.com/business/energy/saudi-aramco-offers-crude-outside-hormuz-some-asian-refiners-sources-say-2026-08-17/"],
        "notes": "GLOBAL_CRUDE; SELLER_SUPPLIER. Outside Cuba. Market/supply signal only; not an open broker allocation without direct verified access.",
    },
    {
        "scout_name": "SAHJONY CEO Crude Origination",
        "business_name": "Glencore",
        "country": "GB",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Global commodity trader with recent crude supply activity including sale of West African grades to HPCL and a processing/supply contract at Germany's Wilhelmshaven refinery.",
        "source_url": "https://www.reuters.com/business/energy/glencore-wins-processing-contract-germanys-wilhelmshaven-oil-refinery-2026-07-30/",
        "source_description": "Reuters reporting on Glencore crude/refining activity",
        "evidence_urls": ["https://www.reuters.com/business/energy/glencore-wins-processing-contract-germanys-wilhelmshaven-oil-refinery-2026-07-30/"],
        "notes": "GLOBAL_CRUDE; SELLER_SUPPLIER. Outside Cuba. Institutional supply/trader lead; require direct authorized commercial channel for any deal.",
    },
]


async def ensure_energy_crm_seed() -> dict:
    backend = get_backend()
    inserted = 0
    existing_count = 0
    failures: list[dict] = []

    for raw in ENERGY_CRM_LEADS:
        try:
            payload = LeadScoutIn(**raw, consent_to_business_contact=False)
            fp = fingerprint(payload)
            existing = await backend.select("lead_scout_leads", params={"fingerprint": f"eq.{fp}", "limit": "1"}) or []
            if existing:
                existing_count += 1
                continue

            score = opportunity_score(payload)
            ts = now()
            lead_id = f"lsl_{secrets.token_urlsafe(10)}"
            row = {
                "lead_id": lead_id,
                "fingerprint": fp,
                "scout_name": payload.scout_name.strip(),
                "scout_code": "CEO-ENERGY-SEED",
                "scout_contact": None,
                "business_name": payload.business_name.strip(),
                "contact_name": (payload.contact_name or "").strip() or None,
                "email": payload.email,
                "phone": (payload.phone or "").strip() or None,
                "country": payload.country.strip(),
                "city_region": (payload.city_region or "").strip() or None,
                "deal_side": payload.deal_side,
                "lead_type": payload.lead_type,
                "product_need_or_offer": payload.product_need_or_offer.strip(),
                "estimated_deal_value": payload.estimated_deal_value,
                "currency": payload.currency,
                "source_url": (payload.source_url or "").strip() or None,
                "source_description": (payload.source_description or "").strip() or None,
                "evidence_urls": payload.evidence_urls,
                "notes": (payload.notes or "").strip() or None,
                "consent_to_business_contact": False,
                "opportunity_score": score,
                "qualification_priority": priority(score),
                "status": "NEW",
                "duplicate_candidate": False,
                "duplicate_of_lead_id": None,
                "referral_credit_status": "NOT_APPLICABLE",
                "commission_status": "NOT_APPLICABLE",
                "created_at": ts,
                "updated_at": ts,
            }
            await backend.insert("lead_scout_leads", row)
            await backend.insert("lead_scout_audit", {
                "event_id": f"lsa_{secrets.token_urlsafe(10)}",
                "lead_id": lead_id,
                "event_type": "ceo_energy_seed_ingested",
                "summary": "CEO energy/crude research lead ingested into Country CRM",
                "payload": {
                    "score": score,
                    "priority": priority(score),
                    "deal_side": payload.deal_side,
                    "lead_type": payload.lead_type,
                    "source_url": payload.source_url,
                    "automatic_promotion": False,
                },
                "created_at": ts,
            })
            inserted += 1
        except Exception as exc:
            failures.append({"business_name": raw.get("business_name"), "error": type(exc).__name__})

    return {
        "status": "ok" if not failures else "partial",
        "expected": len(ENERGY_CRM_LEADS),
        "inserted": inserted,
        "already_present": existing_count,
        "failed": len(failures),
        "failures": failures,
        "automatic_deal_promotion": False,
        "automatic_outreach_authority": False,
    }
