(()=>{
const LOCALES=[['en-US','English'],['es','Español'],['fr','Français'],['pt-BR','Português'],['de','Deutsch'],['it','Italiano'],['nl','Nederlands'],['pl','Polski'],['ru','Русский'],['uk','Українська'],['tr','Türkçe'],['ar','العربية'],['he','עברית'],['fa','فارسی'],['ur','اردو'],['hi','हिन्दी'],['bn','বাংলা'],['pa','ਪੰਜਾਬੀ'],['ta','தமிழ்'],['te','తెలుగు'],['mr','मराठी'],['gu','ગુજરાતી'],['zh-Hans','简体中文'],['zh-Hant','繁體中文'],['ja','日本語'],['ko','한국어'],['vi','Tiếng Việt'],['th','ไทย'],['id','Bahasa Indonesia'],['ms','Bahasa Melayu'],['fil','Filipino'],['sw','Kiswahili'],['am','አማርኛ'],['ha','Hausa'],['yo','Yorùbá'],['ig','Igbo'],['zu','isiZulu'],['af','Afrikaans'],['el','Ελληνικά'],['cs','Čeština'],['ro','Română'],['hu','Magyar'],['sv','Svenska'],['no','Norsk'],['da','Dansk'],['fi','Suomi']];
const RTL=new Set(['ar','fa','he','ur','ps','sd','ug','yi']);
const path=location.pathname;const role=path.startsWith('/owner')?'owner':path.startsWith('/customer')?'customer':'employee';
let locale=localStorage.getItem('sahjony.locale')||navigator.language||'en-US';if(!LOCALES.some(x=>x[0]===locale))locale=(LOCALES.find(x=>x[0]===locale.split('-')[0])||['en-US'])[0];
function headers(){const token=document.getElementById('token')?.value||'';const h={'Content-Type':'application/json','X-Role':role};if(token)h.Authorization='Bearer '+token;if(role==='employee')h['X-Employee-Id']=document.getElementById('employeeId')?.value||'staff';return h}
function applyDir(){const l=locale.toLowerCase().split('-')[0];document.documentElement.lang=locale;document.documentElement.dir=RTL.has(l)?'rtl':'ltr';}
function mount(){if(document.getElementById('globalLanguageControl'))return;const box=document.createElement('div');box.id='globalLanguageControl';box.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9999;display:flex;gap:6px;align-items:center;padding:8px;background:rgba(7,17,31,.94);border:1px solid rgba(255,255,255,.18);border-radius:14px;backdrop-filter:blur(12px);font:12px Inter,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;direction:ltr';const s=document.createElement('select');s.id='globalLocale';s.style.cssText='max-width:155px;background:#07111f;color:#fff;border:1px solid rgba(255,255,255,.18);border-radius:9px;padding:8px';LOCALES.forEach(([v,n])=>{const o=document.createElement('option');o.value=v;o.textContent=n;o.selected=v===locale;s.appendChild(o)});const b=document.createElement('button');b.type='button';b.textContent='Translate';b.style.cssText='border:0;border-radius:9px;padding:8px 10px;font-weight:800;cursor:pointer;background:#79f2c0;color:#03111b';s.onchange=()=>{locale=s.value;localStorage.setItem('sahjony.locale',locale);applyDir();savePreference();if(locale!=='en-US')translatePage()};b.onclick=translatePage;box.append(s,b);document.body.appendChild(box)}
function candidateElements(){return [...document.querySelectorAll('h1,h2,h3,h4,p,small,label,button,a,.metric,.step,.security,.empty,.nav,.role')].filter(el=>!el.closest('#globalLanguageControl')&&!el.children.length&&el.textContent.trim().length>0&&el.textContent.trim().length<=700)}
async function translatePage(){if(locale==='en-US'){restore();return}const els=candidateElements();const texts=[];const map=[];for(const el of els){if(!el.dataset.i18nOriginal)el.dataset.i18nOriginal=el.textContent;const t=el.dataset.i18nOriginal.trim();if(t&&texts.length<100){texts.push(t);map.push(el)}}if(!texts.length)return;try{const r=await fetch('/language/translate-batch',{method:'POST',headers:headers(),body:JSON.stringify({texts,target_locale:locale,source_type:'ui'})});const j=await r.json();if(!r.ok)throw new Error(j.detail||'Translation unavailable');(j.translations||[]).forEach((x,i)=>{if(map[i]&&x.text)map[i].textContent=x.text});applyDir()}catch(e){console.warn('SAHJONY translation:',e.message)}}
function restore(){document.querySelectorAll('[data-i18n-original]').forEach(el=>{el.textContent=el.dataset.i18nOriginal;delete el.dataset.i18nOriginal});applyDir()}
async function savePreference(){try{await fetch('/language/preferences',{method:'PUT',headers:headers(),body:JSON.stringify({primary_locale:locale,fallback_locale:'en-US',auto_translate:true,bilingual_view:true,translate_messages:true,translate_documents:false,translate_notifications:true,require_human_review_for_legal:true,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'})})}catch(_){} }
async function loadPreference(){if(!document.getElementById('token')?.value)return;try{const r=await fetch('/language/preferences',{headers:headers()});if(!r.ok)return;const j=await r.json();if(j.preferences?.primary_locale){locale=j.preferences.primary_locale;localStorage.setItem('sahjony.locale',locale);const s=document.getElementById('globalLocale');if(s)s.value=locale;applyDir();if(j.preferences.auto_translate&&locale!=='en-US')translatePage()}}catch(_){} }
document.addEventListener('DOMContentLoaded',()=>{applyDir();mount();const token=document.getElementById('token');if(token)token.addEventListener('change',loadPreference);window.SahjonyI18n={translatePage,restore,loadPreference,getLocale:()=>locale,headers};});
})();