from __future__ import annotations

import secrets
from datetime import datetime, timezone

from insforge_backend import get_backend
from lead_scout_api import LeadScoutIn, fingerprint, opportunity_score, priority


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


# Global energy prospects discovered from current public market intelligence.
# These are research/prospect records only. None are automatically KYC-approved,
# mandate-verified, contracted, or authorized for transaction release.
GLOBAL_ENERGY_CRM_LEADS = [
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Idemitsu Kosan Co., Ltd.",
        "country": "JP",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Japanese refiner actively sourcing Saudi crude via alternative Suez/Cape routes and supplementing supply with UAE and North American crude; recurring institutional crude buyer.",
        "source_url": "https://www.reuters.com/business/energy/idemitsu-starts-sourcing-saudi-crude-via-suez-route-sees-no-risk-stable-supplies-2026-08-18/",
        "source_description": "Reuters report on current Idemitsu crude procurement diversification",
        "evidence_urls": ["https://www.reuters.com/business/energy/idemitsu-starts-sourcing-saudi-crude-via-suez-route-sees-no-risk-stable-supplies-2026-08-18/"],
        "notes": "GLOBAL_CRUDE_BUYER. Current procurement signal; direct counterparty qualification required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Reliance Industries Limited",
        "country": "IN",
        "deal_side": "BOTH",
        "lead_type": "BUYER",
        "product_need_or_offer": "Large export-oriented Indian refiner and crude buyer. Current market intelligence shows direct Venezuelan crude purchases and strong refined-product export capability.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on Reliance direct crude purchases and refinery activity",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/", "https://www.reuters.com/business/energy/us-indian-fuel-exporters-profiting-supply-uncertainty-during-wars-2026-08-19/"],
        "notes": "GLOBAL_CRUDE_BUYER; REFINED_PRODUCTS_SUPPLIER. Verify current tender/procurement channel before outreach.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Nayara Energy Limited",
        "country": "IN",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Export-focused Indian refiner identified as a swing supplier of refined products into tight Asian markets; potential diesel/jet/gasoline supply-side counterparty.",
        "source_url": "https://www.reuters.com/business/energy/us-indian-fuel-exporters-profiting-supply-uncertainty-during-wars-2026-08-19/",
        "source_description": "Reuters report on Indian refiners increasing refined-product exports",
        "evidence_urls": ["https://www.reuters.com/business/energy/us-indian-fuel-exporters-profiting-supply-uncertainty-during-wars-2026-08-19/"],
        "notes": "REFINED_PRODUCTS_SUPPLIER. Product availability and sanctions/origin considerations require deal-specific review.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Phillips 66",
        "country": "US",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "U.S. refiner currently buying Venezuelan Merey 16 heavy crude directly under authorized arrangements; institutional heavy-crude buyer.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on direct Venezuelan crude purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_BUYER. Any Venezuela-related transaction must remain within applicable U.S. authorization and sanctions rules.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Valero Energy Corporation",
        "country": "US",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Major U.S. refiner expected to resume direct purchases of Venezuelan heavy crude and active across global crude/refined-product markets.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on Venezuelan crude buyer pool",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_BUYER. Current loading allocation must be independently confirmed.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Tipco Asphalt Public Company Limited",
        "country": "TH",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Thai asphalt/refining company reported as preparing to resume Venezuelan heavy-crude purchases; potential specialized heavy-crude buyer.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters current crude purchasing report",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_BUYER. Reuters reported purchase preparation but no confirmed loading window at publication.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Repsol S.A.",
        "country": "ES",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "European integrated energy company loading Venezuelan Merey 16 crude directly in 2026 through its authorized commercial arrangements.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on direct crude liftings",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_BUYER. Regulatory authorization and direct counterparty status required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Eni S.p.A.",
        "country": "IT",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "European integrated energy company allocated Venezuelan crude cargoes in 2026 and active in upstream/refining markets.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on crude allocations",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_BUYER. Deal-specific legal and sanctions verification required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Chevron Corporation",
        "country": "US",
        "deal_side": "BOTH",
        "lead_type": "PARTNER",
        "product_need_or_offer": "Integrated major expanding Venezuelan crude production and exports through joint ventures; potential institutional supply/strategic counterparty subject to authorized channels.",
        "source_url": "https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/",
        "source_description": "Reuters report on Chevron crude exports and joint-venture activity",
        "evidence_urls": ["https://www.reuters.com/business/energy/refiners-elbow-traders-take-larger-slice-venezuelas-oil-2026-07-21/"],
        "notes": "GLOBAL_CRUDE_STRATEGIC. Do not infer open allocation or mandate.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Shell plc",
        "country": "GB",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Global major/trader recently sold 2 million barrels of Mars crude to GS Caltex for November arrival; active U.S.-crude supply counterparty.",
        "source_url": "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/",
        "source_description": "Reuters report on current Mars crude sale",
        "evidence_urls": ["https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/"],
        "notes": "GLOBAL_CRUDE_SUPPLIER. Institutional direct access/mandate required before presenting cargo.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Trafigura Group",
        "country": "CH",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Global commodity trader currently supplying crude to Asian refiners and holding fuel-supply rights in Libya; active crude and refined-products supply-side counterparty.",
        "source_url": "https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/",
        "source_description": "Reuters reports on Trafigura crude sales and Libya fuel tenders",
        "evidence_urls": ["https://www.reuters.com/business/energy/asian-refiners-buy-more-us-crude-hormuz-remains-blocked-traders-say-2026-08-14/", "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "GLOBAL_CRUDE_SUPPLIER; REFINED_PRODUCTS_SUPPLIER. Direct commercial onboarding required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Vitol",
        "country": "CH",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "World-scale energy trader with current refined-fuel supply roles including Namibia and Libya, plus broad crude trading activity.",
        "source_url": "https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/",
        "source_description": "Reuters reports on current fuel supply contracts and trading activity",
        "evidence_urls": ["https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/", "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "GLOBAL_ENERGY_SUPPLIER. Institutional onboarding and specific product availability required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "TotalEnergies SE",
        "country": "FR",
        "deal_side": "BOTH",
        "lead_type": "PARTNER",
        "product_need_or_offer": "Integrated major awarded gasoline/diesel supply rights in Libya and participating in large upstream development programs; strategic crude/refined-products counterparty.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on Libya fuel tenders and strategic energy investment",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "GLOBAL_ENERGY_STRATEGIC. No open allocation implied.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "OMV Aktiengesellschaft",
        "country": "AT",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "European energy company awarded fuel-supply tender rights in Libya; candidate gasoline/diesel supply-side counterparty.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on Libya refined-product tender awards",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "REFINED_PRODUCTS_SUPPLIER. Confirm current tender/supply availability.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "BGN International",
        "country": "CH",
        "deal_side": "BOTH",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Commodity trader awarded Libya fuel-supply rights and historically active in crude export liftings; potential crude/refined-products trading counterparty.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on Libya crude and refined-product trading allocations",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "GLOBAL_TRADER. Current allocation volumes and authority must be verified.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Iplom S.p.A.",
        "country": "IT",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Italian refiner awarded fuel-supply tender rights in Libya; candidate Mediterranean gasoline/diesel supplier.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on Libya refined-product tenders",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "REFINED_PRODUCTS_SUPPLIER. Verify current export availability and commercial channel.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Transmed Trading",
        "country": "CH",
        "deal_side": "SELLER",
        "lead_type": "SUPPLIER",
        "product_need_or_offer": "Swiss-based trader reported lifting multiple Libyan crude cargoes in 2026; potential crude supply/trading counterparty.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on Libyan crude cargo allocations",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "GLOBAL_CRUDE_SUPPLIER. Verify current lifting rights and direct authority.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Ampol Limited",
        "country": "AU",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "One of Australia's two largest fuel suppliers, explicitly supported by Export Finance Australia to make additional spot fuel imports during supply shortages.",
        "source_url": "https://www.reuters.com/business/energy/australias-export-credit-agency-underwrite-fuel-imports-by-viva-ampol-boost-2026-04-09/",
        "source_description": "Reuters report on government-backed spot fuel import purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/australias-export-credit-agency-underwrite-fuel-imports-by-viva-ampol-boost-2026-04-09/"],
        "notes": "REFINED_PRODUCTS_BUYER. Strong institutional fuel-import signal; exact product/volume RFQ must be confirmed.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Viva Energy Australia",
        "country": "AU",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Major Australian fuel supplier supported by Export Finance Australia to secure additional spot fuel imports from global sources.",
        "source_url": "https://www.reuters.com/business/energy/australias-export-credit-agency-underwrite-fuel-imports-by-viva-ampol-boost-2026-04-09/",
        "source_description": "Reuters report on government-backed fuel import purchases",
        "evidence_urls": ["https://www.reuters.com/business/energy/australias-export-credit-agency-underwrite-fuel-imports-by-viva-ampol-boost-2026-04-09/"],
        "notes": "REFINED_PRODUCTS_BUYER. Strong institutional fuel-import signal.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Vivo Energy Namibia",
        "country": "NA",
        "deal_side": "BUYER",
        "lead_type": "DISTRIBUTOR",
        "product_need_or_offer": "Namibian fuel distributor and Vitol subsidiary actively seeking alternative Jet A-1 supply after a quarantined shipment disrupted aviation fuel availability.",
        "source_url": "https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/",
        "source_description": "Reuters current report on Jet A-1 shortage and alternative supply search",
        "evidence_urls": ["https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/"],
        "notes": "JET_A1_BUYER_DISTRIBUTOR. Current shortage signal; product specification and procurement channel required.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Discover Airlines",
        "country": "DE",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Lufthansa Group airline experiencing current Jet A-1 supply disruption in Windhoek and actively seeking solutions to reinstate normal fuel supplies.",
        "source_url": "https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/",
        "source_description": "Reuters current report on airline fuel shortage",
        "evidence_urls": ["https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/"],
        "notes": "AVIATION_FUEL_END_USER. Procurement likely routed through airport/fuel suppliers; qualify appropriate commercial channel.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Lufthansa Group",
        "country": "DE",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Global airline group reporting a local jet-fuel shortage at Windhoek suppliers, with fuel procurement and ground teams seeking solutions.",
        "source_url": "https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/",
        "source_description": "Reuters report on current aviation-fuel procurement disruption",
        "evidence_urls": ["https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/"],
        "notes": "AVIATION_FUEL_END_USER. Route through authorized procurement/fuel-supplier channel.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "Namibia Airports Company",
        "country": "NA",
        "deal_side": "BUYER",
        "lead_type": "PARTNER",
        "product_need_or_offer": "Airport operator publicly acknowledging Jet A-1 supply challenges at Namibia's main aviation gateway and coordinating disruption mitigation.",
        "source_url": "https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/",
        "source_description": "Reuters report on Jet A-1 supply disruption at Hosea Kutako International Airport",
        "evidence_urls": ["https://www.reuters.com/world/africa/lufthansas-discover-airlines-says-namibia-fuel-shortage-may-affect-flights-2026-08-20/"],
        "notes": "AVIATION_FUEL_INFRASTRUCTURE. Determine whether procurement authority sits with airport, distributor or concessionaire.",
    },
    {
        "scout_name": "SAHJONY CEO Global Energy Origination",
        "business_name": "National Oil Corporation of Libya (NOC)",
        "country": "LY",
        "deal_side": "BOTH",
        "lead_type": "BUYER",
        "product_need_or_offer": "State oil company purchasing gasoline/diesel via tenders while expanding crude export allocations and seeking major upstream investment to grow production.",
        "source_url": "https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/",
        "source_description": "Reuters report on NOC refined-product tenders and crude export changes",
        "evidence_urls": ["https://www.reuters.com/business/energy/libya-brings-western-traders-blow-russian-fuel-flows-2026-02-18/"],
        "notes": "REFINED_PRODUCTS_BUYER; CRUDE_SELLER; ENERGY_INVESTMENT. Government counterparty; enhanced compliance and formal tender-only engagement.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "Aurora Consulting Ltd",
        "country": "GB",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace RFQ dated August 20, 2026 seeking Jet A-1 at 500,000-2,000,000 barrels per month plus EN590; buyer authority and end-user identity unverified.",
        "source_url": "https://www.tradewheel.com/buyers/jet-a1/",
        "source_description": "Tradewheel current public buyer RFQ listing",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-a1/"],
        "notes": "MARKETPLACE_RQF; AUTHORITY_VERIFICATION_REQUIRED. Require legal entity, end buyer, LOI/ICPO and reasonable RWA before sourcing.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "Crownwin Africa",
        "country": "FR",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace RFQ dated August 21, 2026 seeking initial 100,000 MT petroleum products including EN590, D6 and Jet A-1; authority unverified.",
        "source_url": "https://www.tradewheel.com/buyers/jet-a1/",
        "source_description": "Tradewheel current public buyer RFQ listing",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-a1/"],
        "notes": "MARKETPLACE_RQF; ENHANCED_KYB_REQUIRED. No supplier engagement until buyer authority is established.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "IMA Aviation",
        "contact_name": "Adam Zeggane",
        "country": "GB",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace sourcing inquiry dated August 18, 2026 for Jet A-1 aviation fuel for an end user; legal entity and end-user authority require verification.",
        "source_url": "https://www.tradewheel.com/buyers/jet-a1/",
        "source_description": "Tradewheel current public Jet A-1 buyer listing",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-a1/"],
        "notes": "MARKETPLACE_RQF; AUTHORITY_VERIFICATION_REQUIRED.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "Delco Group",
        "country": "IQ",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Current marketplace buy inquiry for crude oil, LPG/LNG, EN590, diesel and Jet A-1; broad product scope indicates enhanced counterparty verification is necessary.",
        "source_url": "https://www.tradewheel.com/buyers/jet-a1/",
        "source_description": "Tradewheel current petroleum-products buyer listing",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-a1/"],
        "notes": "MARKETPLACE_RQF; HIGH_DILIGENCE. Verify buyer authority, destination, end use and financial capability.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "Angelo Mourao Energy Requirement",
        "contact_name": "Angelo Mourao",
        "country": "US",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace RFQ dated August 7, 2026 seeking long-term Jet A-1 supply around 1,000,000 barrels; buyer entity and authority unverified.",
        "source_url": "https://www.tradewheel.com/buyers/jet-fuel/",
        "source_description": "Tradewheel current Jet A-1 buyer listing",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-fuel/"],
        "notes": "MARKETPLACE_RQF; AUTHORITY_VERIFICATION_REQUIRED.",
    },
    {
        "scout_name": "SAHJONY CEO Marketplace Energy Origination",
        "business_name": "Syed Mohsin Energy Requirement",
        "contact_name": "Syed Mohsin",
        "country": "US",
        "deal_side": "BUYER",
        "lead_type": "BUYER",
        "product_need_or_offer": "Marketplace listings dated July 22, 2026 indicate interest in long-term EN590/D6/Jet A-1 and Jet fuel quantities of 1-5 million barrels; buyer authority unverified.",
        "source_url": "https://www.tradewheel.com/buyers/jet-fuel/",
        "source_description": "Tradewheel public petroleum buyer listings",
        "evidence_urls": ["https://www.tradewheel.com/buyers/jet-fuel/", "https://www.tradewheel.com/buyers/jet-a1/"],
        "notes": "MARKETPLACE_RQF; HIGH_DILIGENCE. Require entity, ICPO/LOI and proof of buyer authority.",
    },
]


async def ensure_global_energy_crm_seed() -> dict:
    backend = get_backend()
    inserted = 0
    already_present = 0
    failures: list[dict] = []

    for raw in GLOBAL_ENERGY_CRM_LEADS:
        try:
            payload = LeadScoutIn(**raw, consent_to_business_contact=False)
            fp = fingerprint(payload)
            existing = await backend.select("lead_scout_leads", params={"fingerprint": f"eq.{fp}", "limit": "1"}) or []
            if existing:
                already_present += 1
                continue

            score = opportunity_score(payload)
            ts = now()
            lead_id = f"lsl_{secrets.token_urlsafe(10)}"
            row = {
                "lead_id": lead_id,
                "fingerprint": fp,
                "scout_name": payload.scout_name.strip(),
                "scout_code": "CEO-GLOBAL-ENERGY-SEED",
                "scout_contact": None,
                "business_name": payload.business_name.strip(),
                "contact_name": (payload.contact_name or "").strip() or None,
                "email": payload.email,
                "phone": (payload.phone or "").strip() or None,
                "country": payload.country.strip(),
                "city_region": (payload.city_region or "").strip() or None,
                "deal_side": payload.deal_side,
                "lead_type": payload.lead_type,
                "product_need_or_offer": payload.product_need_or_offer.strip(),
                "estimated_deal_value": payload.estimated_deal_value,
                "currency": payload.currency,
                "source_url": (payload.source_url or "").strip() or None,
                "source_description": (payload.source_description or "").strip() or None,
                "evidence_urls": payload.evidence_urls,
                "notes": (payload.notes or "").strip() or None,
                "consent_to_business_contact": False,
                "opportunity_score": score,
                "qualification_priority": priority(score),
                "status": "NEW",
                "duplicate_candidate": False,
                "duplicate_of_lead_id": None,
                "referral_credit_status": "NOT_APPLICABLE",
                "commission_status": "NOT_APPLICABLE",
                "created_at": ts,
                "updated_at": ts,
            }
            await backend.insert("lead_scout_leads", row)
            await backend.insert("lead_scout_audit", {
                "event_id": f"lsa_{secrets.token_urlsafe(10)}",
                "lead_id": lead_id,
                "event_type": "ceo_global_energy_seed_ingested",
                "summary": "CEO global energy research lead ingested into CRM",
                "payload": {
                    "score": score,
                    "priority": priority(score),
                    "deal_side": payload.deal_side,
                    "lead_type": payload.lead_type,
                    "source_url": payload.source_url,
                    "automatic_promotion": False,
                },
                "created_at": ts,
            })
            inserted += 1
        except Exception as exc:
            failures.append({"business_name": raw.get("business_name"), "error": type(exc).__name__})

    return {
        "status": "ok" if not failures else "partial",
        "expected": len(GLOBAL_ENERGY_CRM_LEADS),
        "inserted": inserted,
        "already_present": already_present,
        "failed": len(failures),
        "failures": failures,
        "automatic_deal_promotion": False,
        "automatic_outreach_authority": False,
    }
