from __future__ import annotations

import secrets
from datetime import datetime, timezone

from insforge_backend import get_backend
from lead_scout_api import LeadScoutIn, fingerprint, opportunity_score, priority


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


# Publicly identifiable buyer/seller prospects concentrated in import-dependent
# petroleum markets and mid-market distribution channels.  Research records only:
# no mandate, KYC approval, allocation, or transaction authority is implied.
MIDMARKET_OIL_DEPENDENT_LEADS = [
    # Philippines — highly import-dependent petroleum market.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Universal Energy Petroleum Philippines Inc.","country":"PH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Independent petroleum distributor pursuing direct importation and distribution of diesel, gasoline, Jet A-1, bunker fuel, kerosene and lubricants across the Philippines.","source_url":"https://www.universalenergypetroleum.com/","source_description":"Company public site describes import/export and nationwide petroleum distribution plans.","evidence_urls":["https://www.universalenergypetroleum.com/"],"notes":"MID_MARKET; PHILIPPINES; IMPORT_DEPENDENT. Verify DOE accreditation, terminal capacity, current funding and product nominations before commercial terms."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Jetti Petroleum Inc.","country":"PH","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Independent Filipino petroleum company supplying industrial firms, transport terminals and a nationwide retail station network; candidate recurring gasoline/diesel buyer.","source_url":"https://www.jetti.com.ph/home-page/","source_description":"Jetti public site identifies independent fuel distribution and 100+ retail stations.","evidence_urls":["https://www.jetti.com.ph/home-page/"],"notes":"MID_MARKET_DISTRIBUTOR. Confirm current import/procurement desk and approved supplier requirements."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Petrotrade Philippines Inc.","country":"PH","deal_side":"BUYER","lead_type":"BUYER","product_need_or_offer":"Philippine fuel importer/buyer identified in recent shipment analytics for fuel-related imports.","source_url":"https://www.volza.com/p/injection-or-fuel/buyers/buyers-in-philippines/","source_description":"2026 trade-shipment analytics identifies Petrotrade Philippines among active fuel-related importers.","evidence_urls":["https://www.volza.com/p/injection-or-fuel/buyers/buyers-in-philippines/"],"notes":"TRADE_DATA_SIGNAL. Verify legal entity, product specification, volume and procurement authority."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Kitrol Holdings Inc.","country":"PH","deal_side":"BUYER","lead_type":"BUYER","product_need_or_offer":"Active Philippine importer appearing as a leading diesel-fuel/diesel-generator buyer in 2026 shipment data.","source_url":"https://www.volza.com/p/diesel-fuel-or-diesel-generator/buyers/buyers-in-philippines/","source_description":"2026 import analytics reports Kitrol Holdings as the highest-volume buyer in the referenced diesel-fuel/diesel-generator dataset.","evidence_urls":["https://www.volza.com/p/diesel-fuel-or-diesel-generator/buyers/buyers-in-philippines/"],"notes":"TRADE_DATA_SIGNAL; MID_MARKET. Confirm whether demand is bulk fuel, equipment, or both before outreach."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"SL Harbor Bulk Terminal Corp.","country":"PH","deal_side":"BUYER","lead_type":"BUYER","product_need_or_offer":"Bulk-terminal/import prospect appearing among active Philippine fuel-related import buyers.","source_url":"https://www.volza.com/p/injection-or-fuel/buyers/buyers-in-philippines/","source_description":"Trade analytics lists SL Harbor Bulk Terminal Corp. among leading fuel-related importers.","evidence_urls":["https://www.volza.com/p/injection-or-fuel/buyers/buyers-in-philippines/"],"notes":"TERMINAL_BUYER_SIGNAL. Verify terminal role, storage access and current procurement requirements."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"FIL Generators and Services Company","country":"PH","deal_side":"BUYER","lead_type":"BUYER","product_need_or_offer":"Industrial generator and fuel-related importer with substantial shipment activity; candidate diesel-generator/fuel-system buyer.","source_url":"https://www.volza.com/p/diesel-or-fuel/buyers/buyers-in-philippines/hsn-code-8502/","source_description":"2026 trade analytics lists FIL Generators and Services among leading Philippine diesel/fuel generator importers.","evidence_urls":["https://www.volza.com/p/diesel-or-fuel/buyers/buyers-in-philippines/hsn-code-8502/"],"notes":"INDUSTRIAL_ENERGY_BUYER. Confirm whether petroleum demand exists independently of equipment imports."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Marisen Enterprises","country":"PH","deal_side":"BUYER","lead_type":"BUYER","product_need_or_offer":"Active Philippine diesel/fuel generator importer with high shipment counts; candidate industrial energy-equipment buyer.","source_url":"https://www.volza.com/p/diesel-or-fuel/buyers/buyers-in-philippines/hsn-code-8502/","source_description":"2026 trade analytics identifies Marisen Enterprises as a high-volume importer in diesel/fuel generator categories.","evidence_urls":["https://www.volza.com/p/diesel-or-fuel/buyers/buyers-in-philippines/hsn-code-8502/"],"notes":"MID_MARKET; INDUSTRIAL. Specific bulk-fuel demand must be established before fuel outreach."},

    # Bangladesh — LPG market >98% import-dependent.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Omera Petroleum Limited","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Major private LPG importer/distributor in Bangladesh; recurring LPG procurement prospect.","source_url":"https://en.prothomalo.com/business/local/t6llpnd9gl","source_description":"Market reporting identifies Omera as Bangladesh's leading LPG importer by value/share.","evidence_urls":["https://en.prothomalo.com/business/local/t6llpnd9gl","https://www.lpg.com.bd/lpg-supplier"],"notes":"LPG_IMPORTER. Verify procurement cycle, specifications and approved-vendor process."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Petromax LPG Limited","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Private Bangladesh LPG importer/distributor with significant recurring imports.","source_url":"https://en.prothomalo.com/business/local/t6llpnd9gl","source_description":"Market reporting lists Petromax among the largest Bangladesh LPG importers.","evidence_urls":["https://en.prothomalo.com/business/local/t6llpnd9gl"],"notes":"LPG_IMPORTER. Direct procurement authority required."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Meghna Fresh LPG Ltd.","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Growing private LPG importer/distributor that increased market share as Bangladesh's import structure shifted.","source_url":"https://www.thedailystar.net/business/economy/news/big-lpg-importers-sidelined-emerging-players-gain-ground-4118296","source_description":"2026 reporting identifies Meghna Fresh among emerging LPG importers gaining share.","evidence_urls":["https://www.thedailystar.net/business/economy/news/big-lpg-importers-sidelined-emerging-players-gain-ground-4118296","https://en.prothomalo.com/business/local/t6llpnd9gl"],"notes":"GROWTH_LPG_IMPORTER. Verify current letters-of-credit capacity and procurement schedule."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Jamuna Spacetech Joint Venture","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Private Bangladesh LPG importer/distributor with material import share and active market presence.","source_url":"https://en.prothomalo.com/business/local/t6llpnd9gl","source_description":"Market reporting identifies Jamuna Spacetech as a top-five LPG importer.","evidence_urls":["https://en.prothomalo.com/business/local/t6llpnd9gl"],"notes":"LPG_IMPORTER; MID_MARKET/INSTITUTIONAL. Verify current buying desk."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"BM Energy (BD) Ltd.","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Bangladesh LPG importer/distributor with meaningful import market share.","source_url":"https://en.prothomalo.com/business/local/t6llpnd9gl","source_description":"Market reporting lists BM Energy among significant Bangladesh LPG importers.","evidence_urls":["https://en.prothomalo.com/business/local/t6llpnd9gl"],"notes":"LPG_IMPORTER. Verify legal entity and current procurement requirements."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"United Aygaz LPG Ltd.","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Private LPG importer/distributor gaining share in Bangladesh's import-dependent market.","source_url":"https://www.thedailystar.net/business/economy/news/big-lpg-importers-sidelined-emerging-players-gain-ground-4118296","source_description":"2026 market reporting identifies United Aygaz among emerging importers increasing market share.","evidence_urls":["https://www.thedailystar.net/business/economy/news/big-lpg-importers-sidelined-emerging-players-gain-ground-4118296"],"notes":"LPG_IMPORTER. Confirm current supplier onboarding and financing capacity."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Bengal LPG","country":"BD","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Bangladesh LPG supplier/distributor operating in a market that is overwhelmingly dependent on imports.","source_url":"https://www.lpg.com.bd/lpg-supplier","source_description":"Bangladesh LPG industry directory lists Bengal LPG among active suppliers.","evidence_urls":["https://www.lpg.com.bd/lpg-supplier"],"notes":"SME/MID_MARKET LPG channel. Verify import status and purchasing authority."},

    # Pakistan — private OMC buyer/distributor book.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Hascol Petroleum Limited","country":"PK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Pakistan oil marketing company procuring, storing and marketing high-speed diesel, gasoline, fuel oil, LPG and lubricants.","source_url":"https://www.hascol.com/about-us/what-we-do/","source_description":"Company and Pakistan Stock Exchange profiles confirm procurement/storage/marketing business and oil-marketing license.","evidence_urls":["https://www.hascol.com/about-us/what-we-do/","https://dps.psx.com.pk/company/HASCOL"],"notes":"OMC; BUYER/DISTRIBUTOR. Financial/credit review required before offering terms."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Taj Gasoline (Pvt.) Limited","country":"PK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Independent Pakistani fuel retailer/distributor with 118+ sites and four terminals/depots; candidate recurring gasoline/diesel buyer.","source_url":"https://tajgasoline.com/","source_description":"Company site documents nationwide station network and terminal/depot footprint.","evidence_urls":["https://tajgasoline.com/"],"notes":"MID_MARKET OMC. Verify procurement desk and licensed import route."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Gas & Oil Pakistan Limited","country":"PK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Pakistani oil marketing company and potential recurring gasoline/diesel buyer/distributor.","source_url":"https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025","source_description":"Pakistan OMC industry list identifies Gas & Oil Pakistan among licensed marketing companies.","evidence_urls":["https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025"],"notes":"VERIFY_LICENSE_CURRENT via OGRA/official records before outreach."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Flow Petroleum (Pvt.) Limited","country":"PK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Pakistani oil marketing company; candidate refined-products buyer/distributor.","source_url":"https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025","source_description":"Pakistan OMC industry list identifies Flow Petroleum among licensed marketing companies.","evidence_urls":["https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025"],"notes":"MID_MARKET OMC. Confirm current license, storage and procurement authority."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"BE Energy Limited","country":"PK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Pakistani oil marketing company; candidate gasoline/diesel procurement prospect.","source_url":"https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025","source_description":"Pakistan OMC industry list identifies BE Energy among licensed marketing companies.","evidence_urls":["https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025"],"notes":"MID_MARKET OMC. Verify current license and product demand."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Cnergyico Pk Limited","country":"PK","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Pakistani refiner/oil-marketing company and active petroleum-market participant; potential crude/refined-product buyer or seller depending nomination.","source_url":"https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025","source_description":"Pakistan OMC industry list identifies Cnergyico among licensed marketing companies.","evidence_urls":["https://www.scribd.com/document/974602893/Pakistan-OMCs-Review-2025"],"notes":"REFINER/OMC. Verify current crude/product procurement or export requirement before matching."},

    # Nepal — smaller licensed LPG bottlers/distributors with public association contacts.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Ambar Gas Udyog Pvt. Ltd.","email":"ambarkeyal@gmail.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor in an import-dependent national LPG market.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association active-member listing.","evidence_urls":["https://www.lpgnepal.org/members","https://noc.org.np/pages?id=40"],"notes":"SME LPG BUYER/DISTRIBUTOR. Verify current allocation/procurement route through Nepal Oil Corporation framework."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Baba Gas Udyog Pvt. Ltd.","email":"babagas51@yahoo.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor; potential LPG supply-channel prospect.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME LPG channel. Verify procurement mechanism and capacity."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Bhanu Gas Udyog Pvt. Ltd.","email":"bhanugas@yahoo.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor; potential recurring downstream channel.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME LPG channel. Verify capacity and purchasing authority."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Bheri Gas Udyog Pvt. Ltd.","email":"bherigas@gmail.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor serving the Nepalgunj region.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME LPG channel. Verify allocation and current demand."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Everest Gas Udyog Pvt. Ltd.","email":"everestgas@mos.com.np","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Kathmandu-area LPG bottler/distributor and downstream buyer prospect.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME/MID_MARKET LPG channel. Verify email validity and procurement route."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Gauri Shankar Gas Udyog Pvt. Ltd.","email":"himalgas@gmail.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor and downstream market prospect.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME LPG channel. Verify procurement requirements."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Gita Gas Udyog Pvt. Ltd.","email":"gitagas123@gmail.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal LPG bottler/distributor serving Dhading; potential downstream LPG buyer/channel.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME LPG channel. Verify current demand and license status."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Himalayan Petro Chemicals Pvt. Ltd.","email":"kushalmally@gmail.com","country":"NP","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Nepal petroleum/LPG industry participant listed by the national LPG association; potential downstream buyer/distributor.","source_url":"https://www.lpgnepal.org/members","source_description":"Nepal LP Gas Industry Association member listing.","evidence_urls":["https://www.lpgnepal.org/members"],"notes":"SME/MID_MARKET. Verify exact product scope and procurement authority."},

    # Sri Lanka — licensed import/storage/distribution market entrants.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"RM Parks Lanka","country":"LK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Sri Lanka petroleum import/storage/distribution/retail market entrant associated with RM Parks/Shell route.","source_url":"https://www.cabinetoffice.gov.lk/cab/index.php?Itemid=49&dID=11968&id=16&lang=en&option=com_content&view=article","source_description":"Sri Lankan Cabinet decision approved RM Parks for long-term petroleum import/storage/distribution/sale.","evidence_urls":["https://www.cabinetoffice.gov.lk/cab/index.php?Itemid=49&dID=11968&id=16&lang=en&option=com_content&view=article"],"notes":"LICENSED_IMPORT_CHANNEL. Verify current operating entity, Shell relationship and procurement desk."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"United Petroleum Lanka","country":"LK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Approved Sri Lanka petroleum import/storage/distribution/retail operator originating from United Petroleum Pty Ltd.","source_url":"https://www.cabinetoffice.gov.lk/cab/index.php?Itemid=49&dID=11968&id=16&lang=en&option=com_content&view=article","source_description":"Sri Lankan Cabinet decision approved United Petroleum for petroleum import/storage/distribution/sale.","evidence_urls":["https://www.cabinetoffice.gov.lk/cab/index.php?Itemid=49&dID=11968&id=16&lang=en&option=com_content&view=article"],"notes":"LICENSED_IMPORT_CHANNEL. Confirm current license/operations and buying desk."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Sinopec Energy Lanka (Private) Limited","country":"LK","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Sri Lankan importer/distributor of petrol, diesel, Jet A-1, kerosene and furnace oil with a large station-development mandate.","source_url":"https://fuel.sinopec.com/fuel/en/lanka/Profile.shtml","source_description":"Official company profile describes import, storage and distribution license and product categories.","evidence_urls":["https://fuel.sinopec.com/fuel/en/lanka/Profile.shtml"],"notes":"INSTITUTIONAL LOCAL SUBSIDIARY. Procurement likely centralized; qualify route before outreach."},

    # Ghana — official downstream regulator data highlights many mid-market BIDECs.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Fueltrade Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Bulk import, distribution and export petroleum company with leading Ghana market share in regulator statistics.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA downstream bulletin identifies Fueltrade as a leading BIDEC.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"REGULATOR-IDENTIFIED BIDEC. Verify current product nominations and counterparty onboarding."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Juwel Energy Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Ghana bulk import/distribution/export petroleum company with material downstream volumes.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA downstream bulletin lists Juwel Energy among leading BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"MID_MARKET/INSTITUTIONAL BIDEC. Verify current demand/supply position."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Maranatha Oil Services Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Ghana bulk petroleum import/distribution/export company with significant market share.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin lists Maranatha Oil Services among leading BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"BIDEC. Verify product slate and commercial desk."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"GoEnergy Company Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Ghana bulk import/distribution/export petroleum company with substantial regulator-reported sales.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin identifies GoEnergy among leading BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"BIDEC. Verify current procurement/export needs."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Cirrus Oil Services Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Ghana petroleum bulk import/distribution/export company with material downstream volumes.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin lists Cirrus Oil Services among top BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"BIDEC. Verify current product demand and supply capability."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Sage Distribution Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Mid-market Ghana bulk petroleum import/distribution/export company.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin identifies Sage Distribution as an active BIDEC.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"MID_MARKET BIDEC. Strong target for direct buyer/seller qualification."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Astra Oil Services Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Mid-market Ghana bulk petroleum import/distribution/export company.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin identifies Astra Oil Services as an active BIDEC.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"MID_MARKET BIDEC. Verify buying/selling book and credit requirements."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Blue Ocean Energy Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Mid-market Ghana petroleum bulk importer/distributor/exporter.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin identifies Blue Ocean Energy among active BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"MID_MARKET BIDEC. Qualify product slate and procurement needs."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Eagle Petroleum Company Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Mid-market Ghana bulk petroleum import/distribution/export company.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin identifies Eagle Petroleum among active BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"MID_MARKET BIDEC. Verify current product needs."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Reston Energy Trading Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Smaller Ghana bulk petroleum import/distribution/export company; suitable mid-market qualification target.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin reports Reston Energy Trading as an active BIDEC.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"SMALLER BIDEC. Priority for direct commercial qualification."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Ebony Oil & Gas Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Smaller Ghana bulk petroleum importer/distributor/exporter in regulator market statistics.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin lists Ebony Oil & Gas as an active BIDEC.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"SME/MID_MARKET BIDEC. Verify current license and product book."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Oil Channel Limited","country":"GH","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Smaller Ghana bulk petroleum import/distribution/export company.","source_url":"https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf","source_description":"Ghana NPA bulletin lists Oil Channel Limited among active BIDECs.","evidence_urls":["https://npa.gov.gh/wp-content/uploads/2025/05/Petroleum-Downstream-Statistical-Bulletin_Q1-2025.pdf"],"notes":"SME/MID_MARKET BIDEC. Direct qualification target."},

    # Caribbean import-dependent downstream channels.
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Sunix Petroleum, SRL","country":"DO","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Dominican distributor of gasoline, diesel, fuel oil and kerosene serving commercial and retail markets.","source_url":"https://marti.do/empresas","source_description":"Grupo Martí public site describes Sunix downstream product distribution; Dominican procurement records identify Sunix as a fuel supplier.","evidence_urls":["https://marti.do/empresas","https://mem.gob.do/transparencia/cm-2020-0034-adquisicion-de-combustible/"],"notes":"MID_MARKET/INSTITUTIONAL DISTRIBUTOR. Verify current import procurement and supplier registration."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Tropigas Dominicana","country":"DO","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Dominican propane distributor serving industrial, commercial and residential customers; recurring LPG downstream buyer/channel.","source_url":"https://marti.do/empresas","source_description":"Grupo Martí public site identifies Tropigas as a leading propane distributor with 3,000+ customers.","evidence_urls":["https://marti.do/empresas"],"notes":"LPG DISTRIBUTOR. Verify procurement cycle and import structure."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Coastal Petroleum Dominicana","country":"DO","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Dominican/Caribbean fuel-terminal operator providing national and international petroleum terminal services.","source_url":"https://marti.do/empresas","source_description":"Grupo Martí public site describes Coastal as a major modern Caribbean fuel terminal.","evidence_urls":["https://marti.do/empresas"],"notes":"TERMINAL/LOGISTICS + PRODUCT CHANNEL. Verify exact legal entity and current storage/trading services."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"Future Energy Source Company Limited (FESCO)","country":"JM","deal_side":"BUYER","lead_type":"DISTRIBUTOR","product_need_or_offer":"Jamaican-owned distributor of gasoline, automotive diesel, ULSD and lubricants to retail and commercial customers, including manufacturing, construction and transport.","source_url":"https://fescoja.com/about","source_description":"FESCO public profile describes petroleum distribution and bulk commercial fuel supply.","evidence_urls":["https://fescoja.com/about"],"notes":"MID_MARKET JAMAICA DISTRIBUTOR. Verify import source/procurement desk and supplier onboarding."},
    {"scout_name":"SAHJONY CEO Mid-Market Origination","business_name":"SEG-Sideco Ltd","country":"JM","deal_side":"BOTH","lead_type":"DISTRIBUTOR","product_need_or_offer":"Licensed Caribbean fuel logistics/import partner focused on ULSD into Jamaica/CARICOM, with stated capability across Jet A-1, gasoline, LPG, LNG, MGO and other products.","source_url":"https://sourceenergyglobal.com/procurement/seg-sideco-ltd/","source_description":"Company procurement page describes licensed import/logistics role and product capabilities.","evidence_urls":["https://sourceenergyglobal.com/procurement/seg-sideco-ltd/"],"notes":"ENHANCED_KYB_REQUIRED. Validate licenses, actual recent cargo history and authority before relying on product claims."},
]


async def ensure_midmarket_oil_dependent_seed() -> dict:
    backend = get_backend()
    inserted = 0
    already_present = 0
    failures: list[dict] = []

    for raw in MIDMARKET_OIL_DEPENDENT_LEADS:
        try:
            model = LeadScoutIn(**raw, consent_to_business_contact=False)
            fp = fingerprint(model)
            existing = await backend.select("lead_scout_leads", params={"fingerprint": f"eq.{fp}", "limit": "1"}) or []
            if existing:
                already_present += 1
                continue
            score = opportunity_score(model)
            ts = now()
            lead_id = f"lsl_{secrets.token_urlsafe(10)}"
            row = {
                "lead_id": lead_id,
                "fingerprint": fp,
                "scout_name": model.scout_name.strip(),
                "scout_code": "CEO-MIDMARKET-WORLDWIDE",
                "scout_contact": None,
                "business_name": model.business_name.strip(),
                "contact_name": (model.contact_name or "").strip() or None,
                "email": model.email,
                "phone": (model.phone or "").strip() or None,
                "country": model.country.strip(),
                "city_region": (model.city_region or "").strip() or None,
                "deal_side": model.deal_side,
                "lead_type": model.lead_type,
                "product_need_or_offer": model.product_need_or_offer.strip(),
                "estimated_deal_value": model.estimated_deal_value,
                "currency": model.currency,
                "source_url": (model.source_url or "").strip() or None,
                "source_description": (model.source_description or "").strip() or None,
                "evidence_urls": model.evidence_urls,
                "notes": (model.notes or "").strip() or None,
                "consent_to_business_contact": False,
                "opportunity_score": score,
                "qualification_priority": priority(score),
                "status": "NEW",
                "duplicate_candidate": False,
                "duplicate_of_lead_id": None,
                "referral_credit_status": "NOT_APPLICABLE",
                "commission_status": "NOT_APPLICABLE",
                "created_at": ts,
                "updated_at": ts,
            }
            await backend.insert("lead_scout_leads", row)
            await backend.insert("lead_scout_audit", {
                "event_id": f"lsa_{secrets.token_urlsafe(10)}",
                "lead_id": lead_id,
                "event_type": "ceo_midmarket_worldwide_seed_ingested",
                "summary": "Mid-market buyer/seller prospect ingested into governed CRM",
                "payload": {"score": score, "priority": priority(score), "source_url": model.source_url, "automatic_promotion": False},
                "created_at": ts,
            })
            inserted += 1
        except Exception as exc:
            failures.append({"business_name": raw.get("business_name"), "error": type(exc).__name__})

    return {
        "status": "ok" if not failures else "partial",
        "expected": len(MIDMARKET_OIL_DEPENDENT_LEADS),
        "inserted": inserted,
        "already_present": already_present,
        "failed": len(failures),
        "failures": failures,
        "automatic_deal_promotion": False,
        "automatic_outreach_authority": False,
    }
