import {useEffect,useMemo,useState} from 'react';

type Role='owner'|'employee'|'customer';
type ModuleKey='command'|'managed-trade'|'global-sourcing'|'ai-brain'|'countries'|'private-businesses'|'compliance'|'shipping'|'documents'|'messages'|'finance'|'readiness'|'intermediary'|'us-import'|'language'|'sharing';

type ModuleConfig={label:string;health?:string;data?:string;roles:Role[];description:string};

const modules:Record<ModuleKey,ModuleConfig>={
 command:{label:'Command Center',health:'/health',roles:['owner','employee','customer'],description:'Live operating overview, business queues and next actions.'},
 'managed-trade':{label:'Managed Trade',health:'/managed-trade/health',data:'/managed-trade/requests',roles:['owner','employee'],description:'Customer request → supplier → controls → release → delivery → reconciliation.'},
 'global-sourcing':{label:'Worldwide Sourcing',health:'/global-sourcing/health',data:'/global-sourcing/requests',roles:['owner','employee'],description:'Launch and manage worldwide supplier searches by product, budget and destination.'},
 'ai-brain':{label:'AI Brain',health:'/ai-brain/health',roles:['owner','employee'],description:'Governed GPT + Claude decision support with no autonomous release authority.'},
 countries:{label:'Countries',health:'/countries/health',data:'/countries',roles:['owner','employee'],description:'Country activation and corridor controls.'},
 'private-businesses':{label:'Private Businesses',health:'/cuba-private/health',data:'/cuba-private/businesses',roles:['owner','employee'],description:'Cuban private-business verification and eligibility.'},
 compliance:{label:'Compliance',health:'/compliance/health',data:'/compliance',roles:['owner','employee','customer'],description:'Restricted-party, sanctions and transaction evidence.'},
 shipping:{label:'Shipping',health:'/shipments/health',data:'/shipments',roles:['owner','employee','customer'],description:'Shipment milestones, exceptions and logistics follow-up.'},
 documents:{label:'Documents',health:'/documents/health',data:'/documents',roles:['owner','employee','customer'],description:'Trade-document packages and evidence records.'},
 messages:{label:'Communications',health:'/communications/health',data:'/communications/timeline',roles:['owner','employee','customer'],description:'Case communications and customer/partner coordination.'},
 finance:{label:'Finance',health:'/finance/health',data:'/finance/journals',roles:['owner'],description:'Settlement, reconciliation, fees and accounting controls.'},
 readiness:{label:'Business Readiness',health:'/business-readiness/health',data:'/business-readiness/partners',roles:['owner'],description:'Real-world partners, agreements, operational gates and first-live-trade certification.'},
 intermediary:{label:'Intermediary Desk',health:'/intermediary/health',data:'/intermediary/engagements',roles:['owner','employee'],description:'SAHJONY role, compensation, legal-party assignments and engagement economics.'},
 'us-import':{label:'U.S. Import Desk',health:'/us-import/health',roles:['owner','employee'],description:'HTS, customs, IOR, broker, documents, duties and import controls.'},
 language:{label:'Language',health:'/language/health',data:'/language/preferences',roles:['owner','employee','customer'],description:'Worldwide language preferences and communications.'},
 sharing:{label:'Governed Sharing',health:'/collaboration/health',data:'/collaboration/grants',roles:['owner'],description:'Controlled data sharing and access grants.'}
};

const tc=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const esc=(v:any)=>String(v??'—');

function parsePath(){
 const parts=location.pathname.split('/').filter(Boolean);
 if(!parts.length)return {public:true,role:null as Role|null,section:'command' as ModuleKey};
 const role=(['owner','employee','customer'].includes(parts[0])?parts[0]:'owner') as Role;
 const raw=(parts[1]||'command') as ModuleKey;
 return {public:false,role,section:(raw in modules?raw:'command') as ModuleKey};
}

function PublicLanding(){
 const go=(path:string)=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))};
 return <div className="public-site">
   <header className="public-nav">
     <div className="brand-lockup"><div className="brand-mark"/><div><strong>SAHJONY GLOBAL TRADE</strong><span>Worldwide Sourcing · Managed Trade</span></div></div>
     <nav><button onClick={()=>go('/customer')}>Customer Workspace</button><button onClick={()=>go('/employee')}>Employee Access</button><button className="primary" onClick={()=>go('/owner')}>Owner OS</button></nav>
   </header>
   <main>
     <section className="public-hero">
       <div className="hero-copy"><div className="eyebrow">GLOBAL SOURCING · TRADE ORCHESTRATION · DELIVERY</div><h1>Tell us what your business needs. <span>We source the world.</span></h1><p>SAHJONY coordinates supplier discovery, due diligence, commercial terms, trade documentation, compliance, payment paths, logistics, delivery and reconciliation through one governed operating system.</p><div className="hero-actions"><button className="primary large" onClick={()=>go('/customer')}>Start a sourcing request</button><button className="ghost large" onClick={()=>go('/owner')}>Open operating system</button></div><div className="trust-row"><span>Worldwide supplier search</span><span>Fail-closed controls</span><span>AI-assisted operations</span><span>Owner release authority</span></div></div>
       <div className="hero-console"><div className="console-head"><span>TRADE CONTROL PLANE</span><b>LIVE ARCHITECTURE</b></div><div className="console-flow">{['Customer need','Worldwide sourcing','Supplier DD','Commercial terms','Compliance','Payment path','Logistics','Delivery','Reconciliation'].map((x,i)=><div className="flow-step" key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>)}</div></div>
     </section>
     <section className="public-kpis"><article><small>Operating model</small><strong>Managed Trade</strong><p>SAHJONY orchestrates the transaction while roles remain explicit.</p></article><article><small>Coverage</small><strong>Worldwide</strong><p>Country and corridor controls are evaluated transaction by transaction.</p></article><article><small>AI</small><strong>Advisory</strong><p>Models accelerate research and coordination without bypassing release gates.</p></article><article><small>Controls</small><strong>Fail-Closed</strong><p>Missing or failed evidence keeps the transaction on hold.</p></article></section>
     <section className="capabilities"><div><div className="eyebrow">ONE OPERATING SYSTEM</div><h2>From request to reconciled delivery.</h2><p>The public site sells the service. The role-based workspaces run the business.</p></div><div className="cap-grid">{[['Source','Find and compare qualified suppliers worldwide.'],['Qualify','Verify counterparties, product, corridor and evidence.'],['Structure','Set commercial terms, roles, fees and milestones.'],['Execute','Coordinate documents, payment path, logistics and release.'],['Deliver','Track shipment milestones and customer delivery.'],['Reconcile','Close supplier, freight, duty, customer and SAHJONY economics.']].map(([a,b])=><article key={a}><strong>{a}</strong><span>{b}</span></article>)}</div></section>
   </main>
   <footer>SAHJONY Global Trade · Worldwide managed-trade operating system</footer>
 </div>
}

function App(){
 const [route,setRoute]=useState(parsePath());
 useEffect(()=>{const pop=()=>setRoute(parsePath());addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
 if(route.public)return <PublicLanding/>;
 return <OperatingApp role={route.role||'owner'} section={route.section}/>;
}

function OperatingApp({role,section}:{role:Role;section:ModuleKey}){
 const [token,setToken]=useState(()=>sessionStorage.getItem('sahjony.token')||'');
 const [employeeId,setEmployeeId]=useState(()=>sessionStorage.getItem('sahjony.employee')||'staff');
 const [health,setHealth]=useState<any>(null);const [records,setRecords]=useState<any[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [lastRefresh,setLastRefresh]=useState<Date|null>(null);
 const [tradeForm,setTradeForm]=useState({customer:'',product_need:'',specifications:'',quantity:'',budget:'',currency:'USD',destination:'US',delivery:''});
 const [countryForm,setCountryForm]=useState({country_code:'',country_name:'',region:'',default_currency:'',default_locale:''});
 const [biz,setBiz]=useState({legal_name:'',trade_name:'',business_type:'SMALL_PRIVATE_BUSINESS',employee_count:1,province:'',municipality:'',owner_names:''});
 useEffect(()=>{sessionStorage.setItem('sahjony.token',token)},[token]);useEffect(()=>{sessionStorage.setItem('sahjony.employee',employeeId)},[employeeId]);
 const visible=useMemo(()=>Object.entries(modules).filter(([,m])=>m.roles.includes(role)) as [ModuleKey,ModuleConfig][],[role]);
 const headers=(json=false)=>{const h:Record<string,string>={'X-Role':role};if(token)h.Authorization=`Bearer ${token}`;if(role==='employee')h['X-Employee-Id']=employeeId||'staff';if(json)h['Content-Type']='application/json';return h};
 const go=(r:Role,s:ModuleKey='command')=>{const url=`/${r}${s==='command'?'':'/'+s}`;history.pushState({},'',url);dispatchEvent(new PopStateEvent('popstate'))};
 async function request(path:string,opts:RequestInit={}){const r=await fetch(path,{...opts,headers:{...headers(!!opts.body),...(opts.headers||{})}});const j=await r.json().catch(()=>({detail:`HTTP ${r.status}`}));if(!r.ok)throw new Error(j.detail||`HTTP ${r.status}`);return j}
 async function refresh(){setLoading(true);setError('');const cfg=modules[section];try{if(cfg.health){const r=await fetch(cfg.health,{cache:'no-store'});const j=await r.json().catch(()=>({status:r.status}));setHealth({ok:r.ok,...j})}if(cfg.data){if(!token){setRecords([]);setError('Enter your role credential to load protected business records.');return}const j=await request(cfg.data,{cache:'no-store'});const arr=Object.values(j).find(v=>Array.isArray(v)) as any[]|undefined;setRecords(arr||[])}else setRecords([]);setLastRefresh(new Date())}catch(e:any){setRecords([]);setError(e.message||'Unable to load live data')}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[role,section]);
 const healthOk=health?.ok!==false&&(health?.status==='ok'||health?.status==='healthy'||health?.status==='ready'||health?.ok===true);
 const readiness=health?.readiness_score??health?.readiness?.score??health?.score??null;
 async function createTrade(){if(role==='customer')return;setError('');try{await request('/managed-trade/requests',{method:'POST',body:JSON.stringify({requester_type:'BUYER',requester_ref:tradeForm.customer||null,product_need:tradeForm.product_need,specifications:tradeForm.specifications||null,quantity:tradeForm.quantity?Number(tradeForm.quantity):null,target_budget:tradeForm.budget?Number(tradeForm.budget):null,currency:tradeForm.currency||'USD',destination_country:(tradeForm.destination||'US').toUpperCase(),target_delivery_date:tradeForm.delivery||null})});go(role,'managed-trade')}catch(e:any){setError(e.message)} }
 async function launchSourcing(){if(role==='customer')return;setError('');try{await request('/global-sourcing/requests',{method:'POST',body:JSON.stringify({product_need:tradeForm.product_need,specifications:tradeForm.specifications||null,quantity:tradeForm.quantity?Number(tradeForm.quantity):null,destination_country:(tradeForm.destination||'US').toUpperCase(),worldwide_search:true,target_budget:tradeForm.budget?Number(tradeForm.budget):null,currency:tradeForm.currency||'USD',target_delivery_date:tradeForm.delivery||null})});go(role,'global-sourcing')}catch(e:any){setError(e.message)} }
 async function addCountry(){try{await request('/countries',{method:'POST',body:JSON.stringify(countryForm)});setCountryForm({country_code:'',country_name:'',region:'',default_currency:'',default_locale:''});refresh()}catch(e:any){setError(e.message)}}
 async function addPrivateBusiness(){try{await request('/cuba-private/businesses',{method:'POST',body:JSON.stringify({...biz,employee_count:Number(biz.employee_count),owner_names:biz.owner_names.split(',').map(x=>x.trim()).filter(Boolean),ownership_evidence_document_ids:[],business_categories:[],state_entity_involvement:null,state_entity_involvement_level:'NONE',prohibited_official_owner:false,prohibited_party_member_owner:false,government_owned:false,government_operated:false,government_controlled:false,uses_cuban_owned_bank:false})});refresh()}catch(e:any){setError(e.message)}}
 const roleCopy=role==='owner'?{label:'OWNER COMMAND CENTER',headline:'See the trade. Know the risk. Move with evidence.',sub:'Executive control for global sourcing, managed trade, counterparties, compliance, logistics, finance, AI and final release.'}:role==='employee'?{label:'STAFF OPERATIONS',headline:'Work the queue. Verify the evidence. Escalate the exceptions.',sub:'Employee operations for sourcing, buyer intelligence, documents, shipment follow-up, HTS research and compliance evidence.'}:{label:'CUSTOMER WORKSPACE',headline:'See your request. Track the trade. Keep every document together.',sub:'Customer-facing visibility into communications, documents, shipment progress, compliance evidence and service status.'};
 return <div className={`os-shell role-${role}`}>
   <aside className="os-side"><button className="brand-button" onClick={()=>{history.pushState({},'','/');dispatchEvent(new PopStateEvent('popstate'))}}><div className="brand-mark"/><div><strong>SAHJONY GLOBAL TRADE</strong><span>{role==='owner'?'Intelligence Operating System':role==='employee'?'Employee Operations Workspace':'Customer Trade Workspace'}</span></div></button><div className="scope-badge">{roleCopy.label}</div><nav>{visible.map(([k,m])=><button key={k} className={section===k?'active':''} onClick={()=>go(role,k)}><span>{m.label}</span></button>)}</nav></aside>
   <main className="os-main"><header className="os-top"><div><span className="eyebrow">{roleCopy.label}</span><strong>{modules[section].label}</strong></div><div className="auth-row"><select value={role} onChange={e=>go(e.target.value as Role)}><option value="owner">Owner</option><option value="employee">Employee</option><option value="customer">Customer</option></select><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder={`${tc(role)} credential`}/>{role==='employee'&&<input value={employeeId} onChange={e=>setEmployeeId(e.target.value)} placeholder="Employee ID"/>}<button onClick={refresh}>Refresh</button></div></header>
   {section==='command'?<CommandDashboard role={role} copy={roleCopy} health={health} healthOk={healthOk} readiness={readiness} go={go} tradeForm={tradeForm} setTradeForm={setTradeForm} createTrade={createTrade} launchSourcing={launchSourcing} error={error}/>:<ModuleWorkspace role={role} section={section} config={modules[section]} health={health} healthOk={healthOk} records={records} loading={loading} error={error} lastRefresh={lastRefresh} refresh={refresh} countryForm={countryForm} setCountryForm={setCountryForm} addCountry={addCountry} biz={biz} setBiz={setBiz} addPrivateBusiness={addPrivateBusiness}/>} 
   </main>
 </div>
}

function CommandDashboard({role,copy,health,healthOk,readiness,go,tradeForm,setTradeForm,createTrade,launchSourcing,error}:any){
 const ownerStats=[['ACTIVE AGENTS','13','Policy-governed registry'],['AI BRAIN',health?.status||'GATED','Advisory decision engine'],['COMPLIANCE','STRICT','Fail-closed release'],['READINESS',readiness!==null?`${readiness}/100`:'LIVE','Infrastructure gate']];
 const employeeStats=[['WORKSPACE','Operations','Employee-facing scope'],['MARKET DATA','Live','Global aggregate signals'],['HTS / SANCTIONS','Evidence','Official-source research'],['RELEASE AUTHORITY','Restricted','Owner / authorized review']];
 const customerStats=[['REQUESTS','Tracked','Managed trade visibility'],['DOCUMENTS','Shared','Case document package'],['SHIPPING','Tracked','Milestones and exceptions'],['RELEASE','Governed','No hidden approvals']];
 const stats=role==='owner'?ownerStats:role==='employee'?employeeStats:customerStats;
 return <><section className="command-hero"><div><div className="eyebrow">{copy.label}</div><h1>{copy.headline}</h1><p>{copy.sub}</p><div className="hero-chip-row"><span>Fail-closed governance</span><span>AI advisory</span><span>Evidence-driven release</span><span>{healthOk?'Production online':'Runtime attention'}</span></div></div><div className="hero-status"><small>OPERATING STATE</small><strong>{healthOk?'ONLINE':'CHECK'}</strong><div><span>Release policy</span><b>FAIL-CLOSED</b></div><div><span>Final authority</span><b>{role==='owner'?'OWNER':'RESTRICTED'}</b></div></div></section>
 <section className="metric-grid">{stats.map(([a,b,c]:string[])=><article key={a}><small>{a}</small><strong>{b}</strong><span>{c}</span></article>)}</section>
 {error&&<div className="error-banner">{error}</div>}
 {role!=='customer'&&<section className="action-grid"><div className="action-card primary-card"><div className="section-title"><div><small>BUSINESS ACTION CENTER</small><h2>Start a real customer trade</h2></div><span>Creates live records</span></div><div className="trade-form"><input value={tradeForm.customer} onChange={e=>setTradeForm({...tradeForm,customer:e.target.value})} placeholder="Customer / business reference"/><input value={tradeForm.product_need} onChange={e=>setTradeForm({...tradeForm,product_need:e.target.value})} placeholder="Product needed"/><textarea value={tradeForm.specifications} onChange={e=>setTradeForm({...tradeForm,specifications:e.target.value})} placeholder="Specifications, model, grade, packaging, use case"/><input type="number" value={tradeForm.quantity} onChange={e=>setTradeForm({...tradeForm,quantity:e.target.value})} placeholder="Quantity"/><input type="number" value={tradeForm.budget} onChange={e=>setTradeForm({...tradeForm,budget:e.target.value})} placeholder="Target budget"/><input value={tradeForm.currency} onChange={e=>setTradeForm({...tradeForm,currency:e.target.value.toUpperCase()})} placeholder="Currency"/><input value={tradeForm.destination} onChange={e=>setTradeForm({...tradeForm,destination:e.target.value.toUpperCase()})} placeholder="Destination ISO code"/><input type="date" value={tradeForm.delivery} onChange={e=>setTradeForm({...tradeForm,delivery:e.target.value})}/><div className="form-actions"><button onClick={createTrade}>Create Managed Trade Request</button><button className="secondary" onClick={launchSourcing}>Launch Worldwide Sourcing</button></div></div></div><div className="action-card"><div className="section-title"><div><small>OPERATING WORKSPACES</small><h2>Run the business</h2></div></div><div className="launcher">{[['managed-trade','Managed Trade','Customer request to reconciliation'],['global-sourcing','Worldwide Sourcing','Supplier search and corridor controls'],['compliance','Compliance','Sanctions and evidence'],['shipping','Shipping','Milestones and exceptions'],['documents','Documents','Trade-document package'],['messages','Communications','Customer and partner coordination'],...(role==='owner'?[['finance','Finance','Settlement and reconciliation'],['readiness','Business Readiness','Partners and launch gates']]:[])].map((x:any)=><button key={x[0]} onClick={()=>go(role,x[0])}><strong>{x[1]}</strong><span>{x[2]}</span></button>)}</div></div></section>}
 {role==='customer'&&<section className="action-grid customer-grid"><div className="action-card primary-card"><div className="section-title"><div><small>YOUR TRADE</small><h2>Track the work that matters</h2></div></div><div className="launcher">{[['messages','Communications','Messages and case updates'],['documents','Documents','Shared trade documents'],['shipping','Shipping','Shipment progress and exceptions'],['compliance','Compliance','Evidence and release status'],['language','Language','Communication preferences']].map((x:any)=><button key={x[0]} onClick={()=>go(role,x[0])}><strong>{x[1]}</strong><span>{x[2]}</span></button>)}</div></div><div className="action-card"><small>HOW SAHJONY OPERATES</small><h2>One accountable workflow</h2><ol className="process-list"><li>Define the business need</li><li>Source and compare suppliers</li><li>Verify commercial and compliance evidence</li><li>Coordinate payment and logistics milestones</li><li>Track delivery and reconcile the transaction</li></ol></div></section>}
 </>
}

function ModuleWorkspace({role,section,config,health,healthOk,records,loading,error,lastRefresh,refresh,countryForm,setCountryForm,addCountry,biz,setBiz,addPrivateBusiness}:any){
 return <><section className="module-hero"><div><div className="eyebrow">{config.label.toUpperCase()}</div><h1>{config.label}</h1><p>{config.description}</p></div><div className={`runtime-badge ${healthOk?'ok':''}`}><span>{healthOk?'LIVE':'CHECK'}</span><small>{config.health||'runtime'}</small></div></section>
 <section className="metric-grid compact"><article><small>Runtime</small><strong>{healthOk?'Connected':'Attention'}</strong><span>Live API state</span></article><article><small>Records</small><strong>{records.length}</strong><span>Visible in this role</span></article><article><small>Authority</small><strong>{role==='owner'?'Executive':role==='employee'?'Scoped':'View'}</strong><span>Role-governed</span></article><article><small>Last refresh</small><strong>{lastRefresh?lastRefresh.toLocaleTimeString():'—'}</strong><span>{loading?'Refreshing…':'Current session'}</span></article></section>
 {error&&<div className="error-banner">{error}</div>}
 {section==='countries'&&role!=='customer'&&<section className="action-card standalone"><div className="section-title"><div><small>COUNTRY ACTIVATION</small><h2>Create a blocked country profile</h2></div></div><div className="inline-form"><input value={countryForm.country_code} onChange={(e:any)=>setCountryForm({...countryForm,country_code:e.target.value.toUpperCase()})} placeholder="ISO code"/><input value={countryForm.country_name} onChange={(e:any)=>setCountryForm({...countryForm,country_name:e.target.value})} placeholder="Country name"/><input value={countryForm.region} onChange={(e:any)=>setCountryForm({...countryForm,region:e.target.value})} placeholder="Region"/><input value={countryForm.default_currency} onChange={(e:any)=>setCountryForm({...countryForm,default_currency:e.target.value.toUpperCase()})} placeholder="Currency"/><input value={countryForm.default_locale} onChange={(e:any)=>setCountryForm({...countryForm,default_locale:e.target.value})} placeholder="Locale"/><button onClick={addCountry}>Create profile</button></div></section>}
 {section==='private-businesses'&&role!=='customer'&&<section className="action-card standalone"><div className="section-title"><div><small>COUNTERPARTY INTAKE</small><h2>Register Cuban private business</h2></div></div><div className="inline-form"><input value={biz.legal_name} onChange={(e:any)=>setBiz({...biz,legal_name:e.target.value})} placeholder="Legal name"/><input value={biz.trade_name} onChange={(e:any)=>setBiz({...biz,trade_name:e.target.value})} placeholder="Trade name"/><input type="number" value={biz.employee_count} onChange={(e:any)=>setBiz({...biz,employee_count:Number(e.target.value)})} placeholder="Employees"/><input value={biz.owner_names} onChange={(e:any)=>setBiz({...biz,owner_names:e.target.value})} placeholder="Owners, comma separated"/><input value={biz.province} onChange={(e:any)=>setBiz({...biz,province:e.target.value})} placeholder="Province"/><button onClick={addPrivateBusiness}>Register for review</button></div></section>}
 <section className="records-card"><div className="section-title"><div><small>LIVE BUSINESS DATA</small><h2>{config.label} queue</h2></div><button className="secondary" onClick={refresh}>{loading?'Refreshing…':'Refresh queue'}</button></div>{!records.length&&!loading?<div className="empty-state">No records are visible in this role/session yet.</div>:<div className="records-grid">{records.slice(0,100).map((r:any,i:number)=><article key={r.id||r.request_id||r.sourcing_request_id||r.document_id||r.shipment_id||r.country_code||r.private_business_id||i}>{Object.entries(r||{}).filter(([,v])=>['string','number','boolean'].includes(typeof v)).slice(0,7).map(([k,v])=><div key={k}><small>{tc(k)}</small><span>{esc(v)}</span></div>)}</article>)}</div>}</section>
 </>
}

export default App;
