import React from 'react';

type Status='VERIFIED'|'POLICY_VERIFIED'|'TRANSACTION_CHECK';
type Rule={title:string;status:Status;detail:string;source:string;sourceLabel:string};

const rules:Rule[]=[
  {title:'Transformación 129 — comercio exterior directo',status:'POLICY_VERIFIED',detail:'Empresas estatales, privadas y cooperativas pueden realizar directamente operaciones de comercio exterior, previa aprobación del MINCEX. La autorización no es automática.',source:'https://www.granma.cu/cuba/2026-07-11/amplian-las-operaciones-directas-de-comercio-exterior-en-cuba-10-07-2026-21-07-05',sourceLabel:'Granma · 11 Jul 2026'},
  {title:'Resolución MINCEX 126/2026',status:'VERIFIED',detail:'Gaceta Oficial No. 73 (3 Sep 2026): procedimiento para concesión de facultades, otorgamiento/modificación/cancelación de nomenclaturas de mercancías de importación y exportación y permisos eventuales.',source:'https://cuba.vlex.com/vid/diario-oficial-republica-cuba-1133233710',sourceLabel:'Gaceta Oficial No. 73 · GOC-2026-487-O73'},
  {title:'Decreto-Ley 108 / Decreto 134 — Aduanas',status:'VERIFIED',detail:'Marco aduanero vigente para formalización, autorización, regímenes aduaneros, desaduanamiento, representación y control de mercancías. Importar directamente no elimina las formalidades de Aduana.',source:'https://www.directoriocubano.com/servicios/gaceta-oficial/2026/ordinaria/7/',sourceLabel:'Gaceta Oficial No. 7 · 21 Jan 2026'},
  {title:'Decreto 160/2026 — actividades no autorizadas o condicionadas',status:'VERIFIED',detail:'Actualiza las actividades restringidas/condicionadas para empresas privadas, mipymes, cooperativas no agropecuarias y TCP. Debe revisarse junto con la nomenclatura autorizada de cada importador.',source:'https://www.granma.cu/cuba/2026-07-29/flexibilizan-el-ejercicio-de-actividades-para-los-actores-economicos-no-estatales-28-07-2026-20-07-45',sourceLabel:'Granma · 29 Jul 2026'},
  {title:'Decretos 167 y 168/2026 — comercio interior y Registro Central Comercial',status:'VERIFIED',detail:'Actualizan comercio mayorista/minorista y simplifican licencias comerciales. Son relevantes para la venta y distribución en Cuba después de la importación.',source:'https://www.directoriocubano.com/servicios/gaceta-oficial/2026/ordinaria/69/',sourceLabel:'Gaceta Oficial No. 69 · 28 Aug 2026'},
  {title:'U.S. export authorization remains separate',status:'TRANSACTION_CHECK',detail:'Una autorización cubana de importación no convierte automáticamente una exportación desde EE. UU. en permitida. Cada operación debe pasar controles de commodity, end-user/end-use, EAR/BIS y OFAC aplicables.',source:'https://www.bis.gov/cuba',sourceLabel:'U.S. BIS · Cuba guidance'}
];

const importerFields=[
  'Legal entity / registration','MINCEX direct foreign-trade authority','Approved import nomenclature','Permit/eventual permit if applicable','Customs/importer registration','Authorized customs representative or agent','Commodity/product eligibility','Sanctions / ownership screening','U.S. export-control classification','End-user / end-use verification','Payment and banking route','Cuba entry point','Warehouse / customs handling','Last-mile provider','Authorization effective / expiry dates','Evidence source and verification date'
];

const routes=[
  {name:'DIRECT',chain:'Supplier → SAHJONY → Carrier → Authorized Cuban importer → Customs clearance → Delivery',use:'Preferred when the Cuban buyer has verified MINCEX authority and approved nomenclature.'},
  {name:'DIRECT + LOGISTICS',chain:'Supplier → SAHJONY → Carrier → Authorized Cuban importer → Customs/handling provider → Last mile',use:'Preferred when an authorized importer still needs brokerage, terminal, warehouse or distribution services.'},
  {name:'MANAGED IMPORT',chain:'Supplier → SAHJONY → Carrier → Authorized import/intermediary structure → Buyer',use:'Fallback when the customer lacks verified direct-import authority or the commodity requires another authorized structure.'}
];

function badge(status:Status){const bg=status==='VERIFIED'?'#113d31':status==='POLICY_VERIFIED'?'#263b55':'#4a3517';const fg=status==='VERIFIED'?'#73efbc':status==='POLICY_VERIFIED'?'#8ec8ff':'#ffd58a';return <span style={{background:bg,color:fg,border:`1px solid ${fg}44`,borderRadius:999,padding:'5px 8px',fontSize:10,fontWeight:900,letterSpacing:'.08em'}}>{status.replace('_',' ')}</span>}

export default function OwnerCubaTradeCenter(){
  return <main style={s.page}>
    <header style={s.header}><a href="/owner/dashboard" style={s.brand}>SAHJONY <span style={{color:'#66dcff'}}>CUBA TRADE</span></a><nav style={s.nav}><a href="/owner/dashboard" style={s.link}>Owner OS</a><a href="/owner/intelligence" style={s.link}>Intelligence</a><a href="/owner/deals" style={s.link}>Deals</a></nav></header>
    <section style={s.hero}><div><div style={s.eyebrow}>CUBA DIRECT IMPORT · REGULATORY COMMAND CENTER</div><h1 style={s.h1}>Use the <span style={{color:'#66dcff'}}>shortest compliant route</span> to the Cuban buyer.</h1><p style={s.lead}>Default rule: a transitaria is not assumed to be the mandatory commercial intermediary. SAHJONY first verifies whether the Cuban entity has direct foreign-trade authority and the applicable import nomenclature; logistics, customs and last-mile providers are then selected only for the services actually required.</p></div><div style={s.alert}><strong>FAIL-CLOSED GATE</strong><p>CUBA IMPORT AUTHORIZED + U.S. EXPORT AUTHORIZED = SHIPMENT ELIGIBLE.</p><span>No shipment is cleared from policy headlines alone.</span></div></section>

    <section style={s.panel}><div style={s.eyebrow}>REGULATORY REGISTER · AS OF 6 SEP 2026</div><h2 style={s.h2}>Verified rules and operating implications</h2><div style={s.ruleGrid}>{rules.map(r=><article key={r.title} style={s.card}><div style={s.row}><strong style={{fontSize:16}}>{r.title}</strong>{badge(r.status)}</div><p style={s.body}>{r.detail}</p><a href={r.source} target="_blank" rel="noreferrer" style={s.source}>{r.sourceLabel} →</a></article>)}</div></section>

    <section style={s.panel}><div style={s.eyebrow}>ROUTING ENGINE</div><h2 style={s.h2}>Three supported Cuba import paths</h2><div style={s.routeGrid}>{routes.map(r=><article key={r.name} style={s.route}><div style={s.routeName}>{r.name}</div><div style={s.chain}>{r.chain}</div><p style={s.body}>{r.use}</p></article>)}</div></section>

    <section style={s.twoCol}>
      <article style={s.panel}><div style={s.eyebrow}>MIPYME / PRIVATE IMPORTER ONBOARDING</div><h2 style={s.h2}>Evidence required before Direct status</h2><div style={s.list}>{importerFields.map((f,i)=><div key={f} style={s.item}><span style={s.no}>{String(i+1).padStart(2,'0')}</span><span>{f}</span></div>)}</div></article>
      <article style={s.panel}><div style={s.eyebrow}>TRANSITARIA POLICY</div><h2 style={s.h2}>Service provider, not automatic intermediary</h2><p style={s.body}>Aerovaradero, Transcargo, Expedimar, Palco and other qualified operators remain eligible when they add operational value: customs representation where authorized, terminal handling, warehouse, refrigerated handling, container extraction, domestic distribution, POD or claims support.</p><div style={s.callout}><strong>Routing selection</strong><div style={s.body}>Total verified landed cost + SLA + capacity + coverage + compliance + tracking + claims performance + SAHJONY protected margin.</div></div><div style={s.callout}><strong>Pricing isolation</strong><div style={s.body}>Provider rate requested/stored in USD/kg. SAHJONY converts internally to USD/lb and sells Agency/Partner and Retail prices in USD/lb. Supplier net rate and SAHJONY margin remain private.</div></div></article>
    </section>

    <section style={s.panel}><div style={s.eyebrow}>DECISION LOGIC</div><h2 style={s.h2}>Automatic eligibility sequence</h2><div style={s.sequence}>{['Verify Cuban legal entity','Verify MINCEX authority','Verify approved import nomenclature / permit','Verify commodity-specific Cuban requirements','Verify U.S. EAR/BIS/OFAC eligibility','Select carrier and Cuba service stack','Calculate landed economics','Release only after all binding gates pass'].map((x,i)=><div key={x} style={s.step}><span style={s.stepNo}>{i+1}</span><strong>{x}</strong></div>)}</div></section>

    <footer style={s.footer}>SAHJONY LLC · Cuba Trade Regulatory Register · Evidence-backed; legal/compliance determinations remain transaction-specific.</footer>
  </main>
}

const s:Record<string,React.CSSProperties>={
  page:{minHeight:'100vh',background:'radial-gradient(circle at 18% -8%,#12354b 0,#07111d 32%,#04080e 70%)',color:'#f4f8fb',fontFamily:'Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',padding:'0 24px 48px'},
  header:{maxWidth:1320,margin:'0 auto',minHeight:74,display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:'1px solid rgba(255,255,255,.08)',gap:18},brand:{fontWeight:950,letterSpacing:'.08em',fontSize:14,color:'#fff',textDecoration:'none'},nav:{display:'flex',gap:12},link:{color:'#b9c7d3',textDecoration:'none',fontSize:13},
  hero:{maxWidth:1320,margin:'0 auto',padding:'64px 0 38px',display:'grid',gridTemplateColumns:'minmax(0,1.65fr) minmax(280px,.7fr)',gap:24,alignItems:'end'},eyebrow:{fontSize:11,fontWeight:950,letterSpacing:'.16em',color:'#66dcff',marginBottom:13},h1:{fontSize:'clamp(44px,6vw,82px)',lineHeight:.94,letterSpacing:'-.05em',margin:'0 0 18px'},lead:{maxWidth:850,color:'#9fb2c1',fontSize:16,lineHeight:1.65},alert:{border:'1px solid rgba(255,190,90,.35)',background:'rgba(83,49,9,.24)',borderRadius:18,padding:22,color:'#ffd58a'},
  panel:{maxWidth:1320,margin:'16px auto',padding:24,border:'1px solid rgba(255,255,255,.09)',borderRadius:20,background:'rgba(6,14,23,.82)'},h2:{fontSize:28,letterSpacing:'-.035em',margin:'0 0 18px'},ruleGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12},card:{padding:18,border:'1px solid rgba(255,255,255,.08)',borderRadius:15,background:'rgba(255,255,255,.025)'},row:{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'},body:{color:'#93a8b8',fontSize:13,lineHeight:1.6},source:{color:'#66dcff',textDecoration:'none',fontSize:12,fontWeight:800},
  routeGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12},route:{padding:20,border:'1px solid rgba(102,220,255,.13)',borderRadius:16,background:'rgba(102,220,255,.035)'},routeName:{fontSize:12,fontWeight:950,letterSpacing:'.14em',color:'#66dcff'},chain:{fontWeight:850,lineHeight:1.5,marginTop:12},twoCol:{maxWidth:1320,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:16},list:{display:'grid',gap:8},item:{display:'grid',gridTemplateColumns:'34px 1fr',gap:8,padding:'9px 0',borderTop:'1px solid rgba(255,255,255,.06)',fontSize:13},no:{color:'#66dcff',fontWeight:900,fontSize:11},callout:{padding:16,borderRadius:14,background:'rgba(102,220,255,.05)',border:'1px solid rgba(102,220,255,.13)',marginTop:12},sequence:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10},step:{padding:16,borderRadius:14,border:'1px solid rgba(255,255,255,.08)',display:'flex',gap:10,alignItems:'center'},stepNo:{width:26,height:26,borderRadius:999,display:'inline-flex',alignItems:'center',justifyContent:'center',background:'#12354b',color:'#66dcff',fontWeight:900,fontSize:11},footer:{maxWidth:1320,margin:'30px auto 0',paddingTop:16,borderTop:'1px solid rgba(255,255,255,.07)',color:'#627989',fontSize:11,letterSpacing:'.06em'}
};