import {useEffect,useMemo,useState} from 'react';
import {supabase,supabaseConfigured} from './supabase';

type Missing={field:string;question:string};
type Rfq={id:string;source:string;buyer_name?:string;company_name?:string;product?:string;destination_port?:string;destination_country?:string;container_count?:number;container_size?:string;specification?:string;package_format?:string;required_ship_date?:string;completeness_score:number;stage:string;qualification_status:string;missing_fields?:Missing[];next_action?:string;updated_at:string};

const required:[keyof Draft,string][]=[
 ['product','¿Qué producto necesita exactamente?'],['destination_port','¿Cuál es el puerto de destino?'],['destination_country','¿En qué país está el destino?'],['container_count','¿Cuántos contenedores completos necesita?'],['container_size','¿Son contenedores de 20’, 40’ o 40HC?'],['specification','¿Qué especificación o calidad requiere?'],['package_format','¿Qué presentación comercial o formato a granel necesita?'],['required_ship_date','¿Para qué fecha necesita el embarque?']
];
type Draft={buyer_name:string;company_name:string;product:string;destination_port:string;destination_country:string;container_count:string;container_size:string;specification:string;package_format:string;required_ship_date:string;notes:string};
const blank:Draft={buyer_name:'',company_name:'',product:'',destination_port:'',destination_country:'',container_count:'',container_size:'',specification:'',package_format:'',required_ship_date:'',notes:''};

function qualify(d:Draft){const missing=required.filter(([k])=>!String(d[k]??'').trim()).map(([field,question])=>({field:String(field),question}));const score=Math.round(((required.length-missing.length)/required.length)*100);const core=Boolean(d.product&&d.destination_port&&d.container_count&&d.container_size);return {missing,score,stage:score===100?'RFQ_COMPLETE':core?'QUALIFIED_DEMAND':'CONVERSATION',qualification_status:score===100?'QUALIFIED':core?'REVIEW_REQUIRED':'INCOMPLETE'};}

export default function RfqIntakeCenter(){
 const [rows,setRows]=useState<Rfq[]>([]);const [draft,setDraft]=useState<Draft>(blank);const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);
 const q=useMemo(()=>qualify(draft),[draft]);
 async function refresh(){setLoading(true);setStatus('');if(!supabaseConfigured){setStatus('Supabase frontend configuration is unavailable.');setLoading(false);return}const {data,error}=await supabase.from('trade_rfq_intakes').select('id,source,buyer_name,company_name,product,destination_port,destination_country,container_count,container_size,specification,package_format,required_ship_date,completeness_score,stage,qualification_status,missing_fields,next_action,updated_at').order('updated_at',{ascending:false}).limit(100);if(error)setStatus(`Owner RFQ access unavailable: ${error.message}`);else setRows((data||[]) as Rfq[]);setLoading(false)}
 useEffect(()=>{void refresh()},[]);
 async function save(){if(!supabaseConfigured)return setStatus('Supabase is not configured.');const payload={source:'owner_manual',buyer_name:draft.buyer_name||null,company_name:draft.company_name||null,product:draft.product||null,destination_port:draft.destination_port||null,destination_country:draft.destination_country||null,container_count:draft.container_count?Number(draft.container_count):null,container_size:draft.container_size||null,specification:draft.specification||null,package_format:draft.package_format||null,required_ship_date:draft.required_ship_date||null,notes:draft.notes||null,completeness_score:q.score,stage:q.stage,qualification_status:q.qualification_status,missing_fields:q.missing,next_action:q.missing[0]?.question||'Advance to firm supplier pricing',assigned_agent:'SOFIA'};const {error}=await supabase.from('trade_rfq_intakes').insert(payload);if(error)return setStatus(`Save blocked: ${error.message}`);setDraft(blank);setStatus('RFQ captured under governed stage rules.');await refresh()}
 const complete=rows.filter(r=>r.stage==='RFQ_COMPLETE').length,qualified=rows.filter(r=>r.stage==='QUALIFIED_DEMAND').length,incomplete=rows.filter(r=>r.stage==='CONVERSATION').length;
 return <main style={s.page}><header style={s.header}><div><div style={s.kicker}>SOFÍA · COMMERCIAL INTAKE</div><h1 style={s.h1}>Conversation → governed RFQ</h1><p style={s.lead}>Every serious inbound request becomes structured demand. Package size is never confused with container size, and no RFQ advances without product, logistics and timing evidence.</p></div><nav style={s.nav}><a href="/owner/dashboard" style={s.link}>Dashboard</a><a href="/owner/priorities" style={s.link}>Priorities</a><a href="/owner/deals" style={s.link}>Deals</a></nav></header>
 <section style={s.metrics}><article style={s.metric}><small>RFQ complete</small><strong>{complete}</strong></article><article style={s.metric}><small>Qualified demand</small><strong>{qualified}</strong></article><article style={s.metric}><small>Incomplete conversations</small><strong>{incomplete}</strong></article><article style={s.metric}><small>Manual draft completeness</small><strong>{q.score}%</strong></article></section>
 <section style={s.two}><article style={s.panel}><div style={s.kicker}>STRUCTURED INTAKE</div><h2 style={s.h2}>Create / repair an RFQ</h2><div style={s.form}>{(['buyer_name','company_name','product','destination_port','destination_country','container_count','specification','package_format','required_ship_date'] as (keyof Draft)[]).map(k=><label key={k} style={s.label}>{label(k)}<input type={k==='required_ship_date'?'date':k==='container_count'?'number':'text'} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})} style={s.input}/></label>)}<label style={s.label}>Container size<select value={draft.container_size} onChange={e=>setDraft({...draft,container_size:e.target.value})} style={s.input}><option value="">Select</option><option value="20FT">20FT</option><option value="40FT">40FT</option><option value="40HC">40HC</option></select></label><label style={{...s.label,gridColumn:'1/-1'}}>Notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})} style={{...s.input,minHeight:84}}/></label></div><div style={s.gate}><b>{q.stage}</b><span>{q.score}% complete</span><span>{q.qualification_status}</span></div>{q.missing.length>0&&<div style={s.missing}><strong>Sofía should ask next:</strong><ol>{q.missing.map(m=><li key={m.field}>{m.question}</li>)}</ol></div>}<button style={s.primary} onClick={()=>void save()}>Save governed RFQ</button>{status&&<p style={s.status}>{status}</p>}</article>
 <article style={s.panel}><div style={s.kicker}>OPERATING STANDARD</div><h2 style={s.h2}>What the customer receives</h2><div style={s.rule}><b>1. Confirm what is already clear.</b><p>Product, commercial package format, number of full maritime containers, 20'/40'/40HC, destination port and required timing.</p></div><div style={s.rule}><b>2. Ask only missing commercial questions.</b><p>No repeated questions for information the buyer already supplied.</p></div><div style={s.rule}><b>3. Move stages explicitly.</b><p>Conversation → Qualified demand → RFQ complete → Firm supplier pricing → Formal quote → Negotiation → Purchase order.</p></div><div style={s.rule}><b>4. Protect SAHJONY economics.</b><p>Supplier identity and margin logic remain controlled until commercial commitment warrants disclosure.</p></div><div style={s.rule}><b>5. Exactly-once intake.</b><p>The Sofia ingestion endpoint deduplicates by source message ID before creating a new RFQ record.</p></div></article></section>
 <section style={s.panel}><div style={s.kicker}>LIVE RFQ QUEUE</div><h2 style={s.h2}>{loading?'Loading…':'Commercial intake queue'}</h2><div style={s.tableWrap}><table style={s.table}><thead><tr><th>Buyer</th><th>Product</th><th>Containers</th><th>Destination</th><th>Stage</th><th>Complete</th><th>Next action</th><th>Updated</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.company_name||r.buyer_name||'Unknown'}</b><small>{r.source}</small></td><td>{r.product||'—'}</td><td>{r.container_count||'—'} {r.container_size||''}</td><td>{r.destination_port||'—'}{r.destination_country?`, ${r.destination_country}`:''}</td><td><span style={s.pill}>{r.stage}</span></td><td>{r.completeness_score}%</td><td>{r.next_action||'—'}</td><td>{new Date(r.updated_at).toLocaleString('en-US',{timeZone:'America/Chicago'})}</td></tr>)}</tbody></table></div></section>
 <footer style={s.footer}>Houston operating timezone · America/Chicago · RFQ stages are evidence gates, not marketing labels.</footer></main>
}
function label(k:keyof Draft){return ({buyer_name:'Buyer name',company_name:'Company',product:'Product',destination_port:'Destination port',destination_country:'Destination country',container_count:'Full container count',container_size:'Container size',specification:'Specification / quality',package_format:'Commercial package / bulk format',required_ship_date:'Required ship date',notes:'Notes'} as Record<keyof Draft,string>)[k]}
const s:Record<string,any>={page:{minHeight:'100vh',background:'#03070c',color:'#f4f8fb',fontFamily:'Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',padding:28},header:{maxWidth:1500,margin:'0 auto',display:'flex',justifyContent:'space-between',gap:24,alignItems:'end',padding:'28px 0 36px',borderBottom:'1px solid rgba(255,255,255,.08)'},kicker:{fontSize:10,fontWeight:950,letterSpacing:'.17em',color:'#66dcff'},h1:{fontSize:'clamp(42px,6vw,78px)',letterSpacing:'-.055em',lineHeight:.95,margin:'12px 0'},lead:{maxWidth:850,color:'#8fa4b5',lineHeight:1.6},nav:{display:'flex',gap:10,flexWrap:'wrap'},link:{color:'#d7e6ee',textDecoration:'none',padding:'10px 13px',border:'1px solid rgba(255,255,255,.1)',borderRadius:999,fontSize:12},metrics:{maxWidth:1500,margin:'16px auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12},metric:{padding:20,border:'1px solid rgba(255,255,255,.08)',borderRadius:16,background:'#09131d'},two:{maxWidth:1500,margin:'16px auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(360px,1fr))',gap:16},panel:{maxWidth:1500,margin:'16px auto',padding:20,border:'1px solid rgba(255,255,255,.08)',borderRadius:18,background:'#07111a'},h2:{margin:'8px 0 18px',fontSize:28},form:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10},label:{display:'grid',gap:6,fontSize:11,color:'#96a9b7'},input:{border:'1px solid rgba(255,255,255,.1)',background:'#050c13',color:'#eef7fb',borderRadius:10,padding:'11px 12px'},gate:{display:'flex',gap:10,flexWrap:'wrap',margin:'16px 0',padding:12,borderRadius:12,background:'rgba(102,220,255,.06)'},missing:{fontSize:12,color:'#a8bac6',lineHeight:1.7},primary:{background:'#66dcff',color:'#021018',border:0,borderRadius:10,padding:'11px 14px',fontWeight:900,cursor:'pointer'},status:{color:'#ffbd6d',fontSize:12},rule:{padding:'12px 0',borderTop:'1px solid rgba(255,255,255,.06)'},tableWrap:{overflow:'auto'},table:{width:'100%',minWidth:1150,borderCollapse:'collapse'},pill:{display:'inline-block',padding:'5px 8px',borderRadius:999,background:'rgba(102,220,255,.1)',color:'#77e3ff',fontSize:9,fontWeight:900},footer:{maxWidth:1500,margin:'24px auto',color:'#6e8291',fontSize:11}};
