import {useEffect,useState} from 'react';

type Health={ready?:boolean;status?:string;tinyfish_ready?:boolean;owner_gate_ready?:boolean;fail_closed?:boolean};

const capabilities=[
 ['Browser execution','TinyFish async agent gateway'],
 ['Risk control','Low-risk autonomy; high-risk actions require approval'],
 ['Evidence','Screenshots, snapshots and element capture'],
 ['Credentials','Server-side key; optional Vault/profile scoping'],
 ['Cost guard','Per-job budget metadata + max-step ceiling'],
 ['Failure mode','Fail closed when secrets, approval or provider are unavailable'],
];

export default function TinyFishControlPlane(){
 const [health,setHealth]=useState<Health>({});
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState('');
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/owner/tinyfish',{cache:'no-store'});const d=await r.json();setHealth(d);if(!r.ok)setError(d?.error||'Gateway unavailable')}catch(e){setError(e instanceof Error?e.message:'Gateway unavailable')}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 const ready=health.ready===true;
 return <main style={s.page}>
  <header style={s.header}><a href="/owner/dashboard" style={s.brand}>SAHJONY <span style={s.accent}>BROWSER OS</span></a><nav style={s.nav}><a href="/owner/dashboard" style={s.link}>Owner OS</a><a href="/owner/jarvis" style={s.link}>JARVIS</a><a href="/owner/intelligence" style={s.link}>Intelligence</a></nav></header>
  <section style={s.hero}><div><div style={s.eyebrow}>PRIVATE OWNER CONTROL PLANE · TINYFISH EXECUTION</div><h1 style={s.h1}>Browser <span style={s.accent}>Operations</span></h1><p style={s.lead}>Governed web execution for SAHJONY. JARVIS decides, policy gates authorize, TinyFish executes, and evidence returns to the operating system.</p></div><div style={{...s.scoreCard,borderColor:ready?'rgba(102,220,255,.35)':'rgba(255,190,92,.35)'}}><div style={s.scoreLabel}>EXECUTION GATE</div><div style={s.score}>{loading?'…':ready?'READY':'LOCKED'}</div><div style={s.muted}>{ready?'Server-side TinyFish and owner gate are configured.':'Fail-closed until required server secrets are configured.'}</div></div></section>
  <section style={s.stats}><Stat label="TinyFish" value={health.tinyfish_ready?'READY':'LOCKED'}/><Stat label="Owner Gate" value={health.owner_gate_ready?'READY':'LOCKED'}/><Stat label="Fail Closed" value={health.fail_closed?'ON':'UNKNOWN'}/><Stat label="Evidence" value="ON"/></section>
  <section style={s.grid}><article style={s.panel}><div style={s.eyebrow}>CONTROL CONTRACT</div><h2 style={s.h2}>10/10 operating safeguards</h2>{capabilities.map(([a,b])=><div key={a} style={s.row}><strong>{a}</strong><span style={s.muted}>{b}</span></div>)}</article><article style={s.panel}><div style={s.eyebrow}>LIVE READINESS</div><h2 style={s.h2}>Gateway state</h2><div style={s.callout}><strong>{ready?'Production execution available':'Execution intentionally blocked'}</strong><p style={s.muted}>{error||(!health.tinyfish_ready?'TINYFISH_API_KEY is not configured. ': '')+(!health.owner_gate_ready?'OWNER_CONTROL_TOKEN is not configured.':'')}</p></div><button onClick={()=>void refresh()} style={s.primary}>Refresh readiness</button><p style={s.note}>No TinyFish API key is exposed to this browser. Consequential actions remain server-gated.</p></article></section>
  <section style={s.panel}><div style={s.eyebrow}>EXECUTION MODEL</div><h2 style={s.h2}>JARVIS → policy → TinyFish → evidence</h2><div style={s.flow}><Flow n="01" t="Intent" d="JARVIS/Sofía defines a verified business outcome."/><Flow n="02" t="Gate" d="Risk, approval, budget and credentials are checked."/><Flow n="03" t="Execute" d="TinyFish runs the web task in strict mode."/><Flow n="04" t="Verify" d="Evidence and outcome determine truthful completion state."/></div></section>
  <footer style={s.footer}>SAHJONY Browser OS · Server-side secrets only · Critical browser actions blocked · Evidence-first execution.</footer>
 </main>
}
function Stat({label,value}:{label:string;value:string}){return <article style={s.stat}><div style={s.statValue}>{value}</div><div style={s.scoreLabel}>{label.toUpperCase()}</div></article>}
function Flow({n,t,d}:{n:string;t:string;d:string}){return <div style={s.flowCard}><span style={s.number}>{n}</span><strong>{t}</strong><p style={s.muted}>{d}</p></div>}
const s:Record<string,any>={page:{minHeight:'100vh',background:'radial-gradient(circle at 15% -10%,#132b43 0,#07101b 36%,#03070c 72%)',color:'#f4f8fb',fontFamily:'Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',padding:'0 24px 48px'},header:{maxWidth:1320,margin:'0 auto',minHeight:74,display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:'1px solid rgba(255,255,255,.08)',gap:20,padding:'10px 0'},brand:{fontWeight:950,letterSpacing:'.09em',fontSize:14,color:'#fff',textDecoration:'none'},accent:{color:'#66dcff'},nav:{display:'flex',gap:8,flexWrap:'wrap'},link:{color:'#aebdca',textDecoration:'none',fontSize:13,padding:'9px 10px'},hero:{maxWidth:1320,margin:'0 auto',padding:'64px 0 34px',display:'grid',gridTemplateColumns:'minmax(0,1.8fr) minmax(260px,.6fr)',gap:28,alignItems:'end'},eyebrow:{fontSize:11,fontWeight:950,letterSpacing:'.16em',color:'#66dcff',marginBottom:12},h1:{fontSize:'clamp(42px,6vw,82px)',lineHeight:.95,letterSpacing:'-.055em',margin:'0 0 18px'},lead:{maxWidth:800,color:'#98adbd',fontSize:16,lineHeight:1.65,margin:0},scoreCard:{border:'1px solid rgba(102,220,255,.22)',background:'rgba(6,18,30,.75)',borderRadius:20,padding:22},scoreLabel:{fontSize:10,fontWeight:950,letterSpacing:'.14em',color:'#91a5b5'},score:{fontSize:38,fontWeight:950,lineHeight:1,margin:'12px 0'},muted:{color:'#8ba0b1',fontSize:12,lineHeight:1.55},stats:{maxWidth:1320,margin:'0 auto 16px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10},stat:{padding:17,border:'1px solid rgba(255,255,255,.08)',borderRadius:15,background:'rgba(7,16,26,.72)'},statValue:{fontSize:22,fontWeight:950,marginBottom:7},grid:{maxWidth:1320,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(330px,1fr))',gap:16},panel:{maxWidth:1320,margin:'16px auto',padding:22,border:'1px solid rgba(255,255,255,.09)',borderRadius:20,background:'rgba(6,14,23,.82)'},h2:{fontSize:27,letterSpacing:'-.035em',margin:'0 0 16px'},row:{display:'grid',gridTemplateColumns:'minmax(120px,.6fr) 1.4fr',gap:16,padding:'13px 0',borderTop:'1px solid rgba(255,255,255,.06)'},callout:{padding:17,borderRadius:13,background:'rgba(102,220,255,.06)',border:'1px solid rgba(102,220,255,.14)',marginBottom:14},primary:{background:'#66dcff',color:'#031018',border:0,borderRadius:10,padding:'11px 15px',fontWeight:950,cursor:'pointer'},note:{fontSize:11,color:'#657b8c',lineHeight:1.5},flow:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10},flowCard:{padding:17,border:'1px solid rgba(255,255,255,.08)',borderRadius:14,background:'rgba(255,255,255,.025)'},number:{fontSize:10,color:'#66dcff',fontWeight:950,letterSpacing:'.13em',display:'block',marginBottom:12},footer:{maxWidth:1320,margin:'28px auto 0',paddingTop:16,borderTop:'1px solid rgba(255,255,255,.07)',color:'#607687',fontSize:11,letterSpacing:'.06em'}};
